### ISSUE TITLE
Sync is getting stuck

### ISSUE THREAD

**Issue by LucyTech** [10up/ElasticPress#3087] opened 2022-10-26 19:49 UTC
I am trying to sync the index on my website but I'm just seeing this in the log file: 
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0
Processed posts 2019 - 2019 of 2021. Last Object ID: 0

**Comment by oscarssanchez** [comment] 2022-10-27 17:15
Closing as it is a duplicate of https://github.com/10up/ElasticPress/issues/3086

**Closed as completed by oscarssanchez** 2022-10-27 17:15 UTC
Labels: question
