### ISSUE TITLE
Test against Gutenberg 10.7/WordPress 5.8

### ISSUE THREAD

**Issue by mckdemps** [10up/ElasticPress#2211] opened 2021-05-21 17:53 UTC
**Is your enhancement related to a problem? Please describe.**

- [ ] Test search block 
- [ ] Test query block 
- [ ] Test autocomplete 

search block: https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Search
query block: https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Query
autocomplete: https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/filters/autocomplete-filters.md

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by dinhtungdu** [comment] 2021-05-27 10:52
Hi @mckdemps,

I tested EP against WP 5.8-alpha-51034 and Gutenberg 10.7.1, here is the results:

**Search block:**
- Generally, EP works seamlessly with the search block, the result is pulled from the ES server. This is expected because the search block is a search form that sends the search query to the search page.
- I found a bug related to the Autosuggest feature. The feature functionalities remain working normally, but the styling is broken because we change the markup of the search form for the suggestion list. I created #2219 to fix this issue.

**Query block:**
EP doesn't have any issue with the query block in my test with Full Site Editing. The posts are served by EP regardless of the type of query (Inherit query from URL or custom query).

**Autocomplete:**
I need more info on this. I searched through the source code of EP and I didn't see the usage of autocomplete filter anywhere.

However, I found a bug with the user autocompleter. Here is the step to reproduce:
1. Setup EP and enable User feature. Activate the Debug Bar ElasticPress plugin. Assume we have an user called `admin.
2. Try to search for `admi`, see `admin` in the list table, and the EP query in the Debug Bar tab.
3. Log the value of `$ep_query` or using xDebug: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/User/QueryIntegration.php#L79
4. Create a new post, at the paragraph block, type `@admi`, see the popover appear with `admin` as the result.
5. Check the log or using xDebug, see the value of `$ep_query` is `false`.

I haven't finished triaging this issue yet, the argument passed to the failed query looks correct but the ES return no result. I will continue debugging this and keep you posted.
<details><summary>Query body of failed ES query</summary>

```
    [27-May-2021 10:33:25 UTC] Array
    (
        [from] => 0
        [size] => 10
        [query] => Array
            (
                [bool] => Array
                    (
                        [should] => Array
                            (
                                [0] => Array
                                    (
                                        [multi_match] => Array
                                            (
                                                [query] => admin
                                                [type] => phrase
                                                [fields] => Array
                                                    (
                                                        [0] => user_login
                                                        [1] => user_nicename
                                                        [2] => display_name
                                                        [3] => user_url
                                                        [4] => user_email
                                                        [5] => meta.first_name
                                                        [6] => meta.last_name
                                                        [7] => meta.nickname
                                                    )

                                                [boost] => 4
                                            )

                                    )

                                [1] => Array
                                    (
                                        [multi_match] => Array
                                            (
                                                [query] => admin
                                                [fields] => Array
                                                    (
                                                        [0] => user_login
                                                        [1] => user_nicename
                                                        [2] => display_name
                                                        [3] => user_url
                                                        [4] => user_email
                                                        [5] => meta.first_name
                                                        [6] => meta.last_name
                                                        [7] => meta.nickname
                                                    )

                                                [boost] => 2
                                                [fuzziness] => 0
                                                [operator] => and
                                            )

                                    )

                                [2] => Array
                                    (
                                        [multi_match] => Array
                                            (
                                                [fields] => Array
                                                    (
                                                        [0] => user_login
                                                        [1] => user_nicename
                                                        [2] => display_name
                                                        [3] => user_url
                                                        [4] => user_email
                                                        [5] => meta.first_name
                                                        [6] => meta.last_name
                                                        [7] => meta.nickname
                                                    )

                                                [query] => admin
                                                [fuzziness] => 1
                                            )

                                    )

                            )

                    )

            )

        [sort] => Array
            (
                [0] => Array
                    (
                        [display_name] => Array
                            (
                                [order] => asc
                            )

                    )

            )

    )
```

</details>

**Comment by Rahmon** [comment] 2021-06-01 14:19
Hi @dinhtungdu 

I've investigated the Autocomplete issue that you described and it's not related to the new versions of Gutenberg/WordPress but it's something we need to fix in the Elasticsearch query. The cause is that the field `display_name` has been used to sort. I'll create an issue to address that.

**Comment by felipeelia** [comment] 2021-06-25 12:41
As #2219 and #2226 are now merged, I'm closing this one out. Thank you very much for the coordinated effort @dinhtungdu and @Rahmon!

**Closed by felipeelia** 2021-06-25 12:41 UTC
Labels: enhancement, high priority
