### ISSUE TITLE
BUG: WP 6.7 Compatability

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#4021] opened 2024-11-27 22:32 UTC
### Describe the bug 
ElasticPress Prevents New Iframe Editor Behavior in WordPress 6.7+

WordPress 6.7 introduced a new method of iframing the post editor. However, ElasticPress appears to block this functionality. A key indicator that the new iframe editor is being used is the presence of the Zoom tool in the top bar

For more context, refer to the [WordPress Core announcement about post editor iframing with meta boxes](https://make.wordpress.org/core/2024/10/18/post-editor-iframing-with-meta-boxes-in-wordpress-6-7/), particularly the "Remaining exception to the iframe" section.

### Likely Cause
ElasticPress registers all its blocks with apiVersion: 2, which likely causes this conflict.

### Steps to Reproduce

1. Install WP 6.7.1
2. Create a new post and observe zoom control in top bar of block editor
3. activate elasticpress
4. observe the zoom control from step 2 is not showing

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/497e1736-f4a6-4c41-8ee9-a308ca929caa)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by psorensen** [comment] 2024-11-27 23:22
Here's a workaround for anyone who might find this. 

```php
function update_all_blocks_to_v_3( $metadata ) {
	$metadata['apiVersion'] = 3;

	return $metadata;
};

add_filter( 'block_type_metadata', 'update_all_blocks_to_v_3' );
```

**Comment by felipeelia** [comment] 2024-12-04 14:03
Closing this as a duplicate of #3853. Hopefully, we'll get some help to have that one done for EP 5.1.4, otherwise it'll be something for EP 5.2.0.

**Closed as completed by felipeelia** 2024-12-04 14:03 UTC
Labels: bug
