### ISSUE TITLE
Facets are disabled on taxonomy archive pages.

### ISSUE THREAD

**Issue by mgratch** [10up/ElasticPress#1304] opened 2019-04-02 06:47 UTC
### Have you searched for similar issues before submitting this one?
Yes, see #1299, I have tested #1301.
### Is this a bug, question or feature request?
Bug.
### Describe the issue you encountered:
When browsing taxonomy archive pages i.e. `wootest.test/product-category/clothing` facets are disabled.
### Current WordPress version:
5.1.1
### Current ElasticPress version:
2.8.2
### Current Elasticsearch version:
6.6.2
### Where do you host your Elasticsearch server:
Self Hosted
### Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
- Query
-  Monitor: by John Blackbourn – 3.3.4
- Debug Bar ElasticPress: by 10up – 1.4
- ElasticPress: by 10up – 2.8.2
- WooCommerce: by Automattic – 3.5.7
- WordPress Importer: by wordpressdotorg – 0.6.4
### Steps to reproduce:
1. Fresh WP Install.
1. Fresh WooCommerce Install.
1. Import Sample WooCommerce Products.
1. Add `awesome` Product Tag to WooCommerce Product (sku) `woo-cap`.
1. Install, setup, and index ElasticPress.
1. Add EP Facet Widget to Sidebar set to display `Product tags`.
1. Browse to the shop page, `https://wootest.test/shop/`. Notice the Product Tag facet is clickable.
1. Browse to a taxonomy archive pages i.e. `wootest.test/product-category/clothing`. Now notice the Product tags facets are disabled.
- _Please note that https://github.com/10up/ElasticPress/blob/2.8.2/features/facets/class-ep-facet-widget.php#L73 is forcing `$term->count` to `0` when in the instance of the **awesome** Product tag there is `1`_

### Screenshots, if needed:
https://drive.google.com/file/d/1HuJTnnPmlSIi48AsqAT-aQPk0KVJzNOE/view

**Comment by oscarssanchez** [comment] 2019-04-06 17:29
Hi @mgratch ,

Thanks for the detailed steps. I confirmed this is also not working for me

**Comment by mgratch** [comment] 2019-04-24 13:53
Hi @oscarssanchez any more info on this? I am finally unblocked elsewhere that I will be digging into this, if you or anyone on the team has further insights that might help, I would appreciate it!

**Comment by oscarssanchez** [comment] 2019-04-30 02:43
Hi @mgratch  i traced down the problem to this line: https://github.com/10up/ElasticPress/blob/develop-2.x/features/facets/facets.php#L292

I have not yet come with an approach to solve the issue, but if you have one that would be great. 

Kind regards,

**Comment by pmgarman** [comment] 2019-05-07 03:25
@oscarssanchez any idea why these views intentionally are not facetable? @tlovett1 looks like that may be your code there any insights you can provide as to why it was disabled so we can find a solution to make it work? Facets aren’t much use if they can’t facet. Having no facets on critical areas like these make this a non starter for us.

**Comment by tlovett1** [comment] 2019-05-14 15:28
Hey @pmgarman, sorry for the delay. I'm not 100% sure why I did it this way. My guess is it just introduces more complexity when you should facets on a tax archive e.g. can't show a facet for the taxonomy you are on. I'll try to put together a quick fix.

**Comment by brandwaffle** [comment] 2019-05-14 16:09
@tlovett1 @pmgarman @mgratch we pushed a potential fix for this in https://github.com/10up/ElasticPress/pull/1301 and it looks like it worked for those who tested. @pmgarman @mgratch does that address the issue or is there something else we need to fix as well?

**Closed** 2019-09-03 19:09 UTC
Labels: enhancement
