### ISSUE TITLE
Facet typeahead selects first Facet in sidebar not current Facet

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#2041] opened 2021-01-20 21:41 UTC
**Describe the bug**

Adding more than one Facet causes the typeahead JS for a later Facet to select the first Facet's data slugs.

**Steps to Reproduce**

1. Create a Facet.
2. Create a second Facet that has multiple options, such as tags, in order to spawn the typeahead field.
3. Type into the typeahead field, and it won't properly limit results to matches. Looking at the function itself reveals it's grabbing the first Facet's data slugs.

**Expected behavior**

Typeahead should work even if previous Facets do not contain a typeahead field (or if they do).

**Screenshots**

**Environment information**
 - Device:  MacBook Pro
 - OS:  MacOS 10.15.7
 - Browser and version:  Chrome LTS
 - WordPress version:  5.6
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by Rahmon** [comment] 2021-02-01 18:27
I'll close this issue as a duplicate of #2003.

**Closed by Rahmon** 2021-02-01 18:27 UTC
Labels: confirmed bug, qa
