### ISSUE TITLE
CPTs are filtered during action_queue_meta_sync

### ISSUE THREAD

**Issue by joliverwestbrook** [10up/ElasticPress#2099] opened 2021-02-21 19:07 UTC
**Describe the bug**
When postmeta is updated for a CPT, the `action_queue_meta_sync` does not sync the post, rather filters it based on posttype not being post or page.

**Steps to Reproduce**
Created a function to update_meta for a CPT and added debug info to the syncmaster file for posts.
Indexable post types returned were only post and page, therefore the update was skipped.

**Expected behavior**
I would hope the expected behavior is to sync all post types previously synced, which the CPTs did get synced during a normal jquery firing of a bulk index.  In settings it would be helpful to have the CPTs listed and the ability to turn them on/off for syncing.

**Workaround**
I worked around this by merging my CPTs into the indexable list using the filter `ep_indexable_post_types`. The CPT array to merge must be in the format: `array( 'cpt_slug' => 'cpt_slug', 'anothercpt_slug' => 'anothercpt_slug' )`

This allowed the CPTs to be recognized as "indexable".

**Comment by felipeelia** [comment] 2021-02-22 11:46
Hi @joliverwestbrook, 

By design, ElasticPress will index only CPTs marked as public, as can be seen [here](https://github.com/10up/ElasticPress/blob/737c50fdb69dcaa7b9acd8852d06e03c41a34724/includes/classes/Indexable/Post/Post.php#L112). Is your CPT public? Can you share here how you are creating it?

Thanks

**Comment by joliverwestbrook** [comment] 2021-02-22 17:45
Hmm, I'll have to take a closer look to verify the settings are correct for EP to pick them up, but yes they are public cpts afaik. I'll find out and get back to you.

**Comment by felipeelia** [comment] 2021-03-15 13:50
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!

**Closed by felipeelia** 2021-03-15 13:50 UTC
Labels: bug, reporter feedback
