### ISSUE TITLE
Order changing status

### ISSUE THREAD

**Issue by blenkhn** [10up/ElasticPress#2826] opened 2022-06-03 05:20 UTC
Hi,

I have a new issue to report.  When I update a status on a woocommerce order the order disappears and then doesn't reappear even after a new sync.  I have to do a "delete and rebuild" for them to show up.  Is there anything that can be done?

I do have to admit that this is with the 4.1 version of the plugin and I have upgraded the plugin now.  I will let you know if it still has a problem.

**Comment by felipeelia** [comment] 2022-06-07 13:21
Hi @blenkhn,

I was not able to reproduce this problem. Do you have any errors in your log files that you could share?

**Comment by blenkhn** [comment] 2022-06-07 17:55
This is still occurring in the new version as well.  I was not able to find anything in the error logs relating to this.

**Comment by blenkhn** [comment] 2022-06-09 03:09
When I deactivate the plugin and teh reactivate the plugin the missing orders that have changed status show up.  very very interesting.

**Comment by oscarssanchez** [comment] 2022-06-18 00:08
Hi @blenkhn , 

Seems like you problem is resolved with the latest version?

**Comment by blenkhn** [comment] 2022-06-25 18:48
Why would I have to reinitialize the plugin to get missing items to show up?

**Comment by felipeelia** [comment] 2022-06-30 19:44
@blenkhn it could be something related to cache. Generally, all cache plugins will flush caches when a plugin is activated or deactivated, and that would explain why the list changed. If the cache solution is not detecting the order status change, that would also explain why the list always remains the same in general.

**Closed as completed** 2022-07-03 20:09 UTC
Labels: reporter feedback
