### ISSUE TITLE
Installation and integration

### ISSUE THREAD

**Issue by MarcusFuto** [10up/ElasticPress#585] opened 2016-09-28 12:11 UTC
I saw your speach on youtube, and I thought I just have to try this awesome thing!
Great presentation by the way! 🎯 

I use a VPS with InmotionHosting for my WP website with WooCommerce. 

They have installed Elasticsearch on my server. 

I have installed ElasticPress plugin.

I have followed these instructions:
http://www.inmotionhosting.com/support/website/elasticsearch/integrating-elasticsearch-with-wordpress-using-elasticpress

When I run this command in ssh: wp elasticpress index --setup

I get this result:

XXX@example.com [~]# wp elasticpress index --setup
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/apc.so' - /usr/lib/php/extensions/no-debug-non-zts-20131226/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0

I have tried to do the same for the root user, but then I do not even get a response. 

What am I doing wrong? 

Also, do I need the ElasticPress Woocommerce plugin or is everything included in ElasticPress 2.1 ?

Help is much appreciated!

Marcus

**Comment by MarcusFuto** [comment] 2016-09-29 08:20
It seems I had upgraded php version to 5.6+ so that my APC did not function. That was the reason for the error ssh. However, when downgrading to 5.4 and installing APC, my website stopped working. I got this error on the screen:
Parse error: syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /home/ringso5/public_html/wp-content/plugins/elasticpress/classes/class-ep-config.php on line 80

I had to go to my plugins folder through ftp and rename the elasticpress plugin. 

Now I am not sure what I should do. 

Any idea what I am doing wrong?

Thanks!

**Comment by AaronHolbrook** [comment] 2016-09-29 19:18
@MarcusFuto looks like this is a duplicate of #581.

I think we can close as that issue has a fix in place.

**Comment by MarcusFuto** [comment] 2016-10-06 12:27
Also, do I need the ElasticPress Woocommerce plugin or is everything included in ElasticPress 2.1 ?

**Comment by tlovett1** [comment] 2016-10-06 15:44
Everything is included in 2.1

**Closed** 2016-10-06 16:12 UTC
