### ISSUE TITLE
Post date(post_date) Maps Date/Time Fields as String -- version 4.1.0

### ISSUE THREAD

**Issue by balajidamodare** [10up/ElasticPress#2801] opened 2022-05-26 10:25 UTC
simply I am indexing data via the command line and its mapping date field as text.
steps to reproduce

`wp elasticpress clear-index`
Output : `Success: Index cleared.`
`wp elasticpress delete-index --yes`
Output `Success: Index deleted
Deleting index for posts...`
`wp elasticpress index --setup --yes --show-bulk-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"`
Output : `Success: Indexing posts...`

Not showing any errors on CLI, shows only success output after running the commands 
**Describe your question**

if I execute the following command then data is crawling and showing progress. this also works as expected but mapping date fields as text.
`wp elasticpress index --show-bulk-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"`
Output: `Success: Indexing posts...
Processed posts 0 - 5 of 8915. Last Object ID: 3151873
Processed posts 5 - 10 of 8915. Last Object ID: 3151798
Processed posts 10 - 15 of 8915. Last Object ID: 3151738
Processed posts 15 - 20 of 8915. Last Object ID: 3151696
Processed posts 20 - 25 of 8915. Last Object ID: 3151660
Processed posts 25 - 30 of 8915. Last Object ID: 3151624
Processed posts 30 - 35 of 8915. Last Object ID: 3151570
Processed posts 35 - 40 of 8915. Last Object ID: 3151556
Processed posts 40 - 45 of 8915. Last Object ID: 3151512
Processed posts 45 - 50 of 8915. Last Object ID: 3151487

Time elapsed: 0.04

Memory Usage: 110.14mb (Peak: 111.93mb)

Processed posts 50 - 55 of 8915. Last Object ID: 3151446
Processed posts 55 - 60 of 8915. Last Object ID: 3151388
Processed posts 60 - 65 of 8915. Last Object ID: 3151354
Processed posts 65 - 70 of 8915. Last Object ID: 3151282
Processed posts 70 - 75 of 8915. Last Object ID: 3151256
Processed posts 75 - 80 of 8915. Last Object ID: 3151197
Processed posts 80 - 85 of 8915. Last Object ID: 3151175
Processed posts 85 - 90 of 8915. Last Object ID: 3151097
Processed posts 90 - 95 of 8915. Last Object ID: 3151067
Processed posts 95 - 100 of 8915. Last Object ID: 3151024

Time elapsed: 0.01 (+-0.03)`

and so on

at the end

Success: Number of posts indexed: 8915
Success: Sync complete
Total time elapsed: 0.100
Success: Done!

**Comment by felipeelia** [comment] 2022-05-26 13:40
Hi @balajidamodare,

Can you please update your ElasticPress version to 4.2.0 and try to run : `wp elasticpress put-mapping` and `wp elasticpress index --show-errors --post-type="videos, tech-101, news, interviews, guest-article, deep-dive, behind-the-scenes, ask-the-cxo, articles"`? FWIW you don't need to run `wp elasticpress delete-index` when you call `put-mapping` or `index` with the `--setup` flag.

**Comment by balajidamodare** [comment] 2022-05-26 16:19
Thank you for the quick response. I will check and update here.

**Comment by balajidamodare** [comment] 2022-05-27 13:22
It's working but I am getting the different errors now.
command: wp elasticpress put-mapping

Error:
Query Response Code: HTTP 400
Query Result: 
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [4]. This limit can be set by changing the [index.max_shingle_diff] index level setting."
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [4]. This limit can be set by changing the [index.max_shingle_diff] index level setting."
    },
    "status": 400
}

```

any plugin settings will help to resolve this.

I am using already one filter to resolve this.
// to resolve max_shingle_diff issue default allowed 5
apply_filters( 'ep_max_shingle_diff', 10 );

**Comment by balajidamodare** [comment] 2022-05-31 05:31
any solution to the above error @felipeelia ??

**Comment by felipeelia** [comment] 2022-05-31 15:26
The problem is already being handled in https://github.com/10up/ElasticPress/issues/2806#issuecomment-1142283294. I'm closing this one out now.

**Closed as completed by felipeelia** 2022-05-31 15:26 UTC
Labels: question
