### ISSUE TITLE
BUG: `ep_post_sync_kill` executed before post meta in DB

### ISSUE THREAD

**Issue by rwrobe** [10up/ElasticPress#2875] opened 2022-06-30 19:22 UTC
**Describe the bug**
Using a metadata flag (via ACF) to prevent a post from being filtered, like so:
```
public function stop_sync( bool $return_val, int $post_id ): bool {
		$should_index = get_post_meta( $post_id, 'searchable', true );

		if ( ! $should_index ) {
			Indexables::factory()->get( 'post' )->delete( $post_id, false );

			return true;
		}

		return $return_val;
	}
```
If I put a breakpoint after it grabs the $should_index value, it evaluates as null. Using the post_id passed into the function, I can also see that the wp_postmeta table doesn't have all the post meta for the post yet.

**Steps to Reproduce**
1. Add the function above hooked to `ep_post_sync_kill`
2. Add an xdebug breakpoint after the meta_data fetch
3. See that the value is null
4. Query the DB and see that the post_id doesn't have the full set of metadata yet

**Expected behavior**
I think this needs to be done after insert_post. Not sure if the order of saving ACF to the DB is later than your hook.

 - WordPress version: 6.0

**Comment by oscarssanchez** [comment] 2022-08-16 02:18
Hi @rwrobe,

Have you tried to reproduce this outside ACF? i tried to reproduce with a standard metabox approach saving meta data on `save_post` and this wasn't a problem for me, however, with ACF I can reproduce what you reported. I'm wondering if the problem is with ACF

**Comment by oscarssanchez** [comment] 2022-08-21 21:31
I've done some testing with Fieldmanager and seems to be the same behavior. Seems like something ElasticPress should change.

**Comment by oscarssanchez** [comment] 2022-09-06 05:27
I dug a bit into FieldManagers code with the latest version of EP and it seems either the code to test is not correct, or something got resolved in the latest version. Here's the code I'm using to test after adding a Checkbox field with FieldManager: 

```
add_filter( 'ep_post_sync_kill', function( $kill, $post_id ) {
    $meta = get_post_meta( $post_id, 'searchable', true );
    if ( ! empty( $meta ) ) {
        return true;
    }
    return $kill;
}, 10, 2 );

```

FieldManager saves post meta on save_post which then will trigger either `updated_post_meta` or `added_post_meta`. I'll close this one since I was not able to reproduce anymore with the latest version. Please feel free to reopen if the issue is not solved.

**Closed as completed by oscarssanchez** 2022-09-06 05:27 UTC
Labels: confirmed bug, bug
