### ISSUE TITLE
Elasticsearch version 6 (6.1.2) support?

### ISSUE THREAD

**Issue by archon810** [10up/ElasticPress#999] opened 2018-01-22 01:44 UTC
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Feature request and bug.

Describe the issue you encountered:
Install latest ES, 6.1.2. Elasticpress complains about compatibility.
Also sync results in "An error occured while syncing" (`{"success":false}`)

Current WordPress version:
4.9.2.

Current ElasticPress version:
2.4

Current Elasticsearch version:
6.1.2

Where do you host your Elasticsearch server:
Locally

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
No.

Steps to reproduce:

1. See above.

Screenshots, if needed:
N/A.

**Comment by archon810** [comment] 2018-01-22 01:58
I can confirm that indexing does start with ES 5.6.6.

**Comment by eugene-manuilov** [comment] 2018-01-24 11:49
This is a duplicate of #995.

**Closed** 2018-01-29 15:52 UTC
