### ISSUE TITLE
Custom search analyzer

### ISSUE THREAD

**Issue by maciejmackowiak** [10up/ElasticPress#1754] opened 2020-04-24 11:08 UTC
Hi,

I want to implement ES search on our website but I've run into a problem
for example I have post like this:
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry.
<a href="https://play.google.com/store/apps/details?id=com.twitter.android&hl=en">some app from google play store</a>
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
```
I would like to find this post by searching for part of an anchor href attribute:
`com.twitter.android`
but it doesn't work.

Can you please tell me how to adjust search results to make it work?

I've tried custom analyzer with pattern tokenizer, but how to properly hook it into ElasticPress?

Thanks in advance
Maciej

**Comment by oscarssanchez** [comment] 2020-05-07 06:00
Hi @maciejmackowiak ,

Do change the mappings, if it is for the post Indexable, you can use the `ep_post_mapping` filter

**Comment by oscarssanchez** [comment] 2020-05-19 13:42
Hi, 

We are closing now this issue as there was no further follow up. If the issue is still not solved, Please feel free to reopen or submit a new issue referencing this one. Thanks!

**Closed by oscarssanchez** 2020-05-19 13:42 UTC
Labels: question
