### ISSUE TITLE
BUG: Mapping Issue - Opensaerch

### ISSUE THREAD

**Issue by balajidamodare** [10up/ElasticPress#2810] opened 2022-05-31 14:53 UTC
**Describe the bug**

While mapping data on Opensaerch getting error.
**Steps to Reproduce**

run following command 
wp elasticpress put-mapping
**Expected behavior**

need to complete the mapping 
**Screenshots**

getting following error
`{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [4]. This limit can be set by changing the [index.max_shingle_diff] index level setting."
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [4]. This limit can be set by changing the [index.max_shingle_diff] index level setting."
    },
    "status": 400
}`
**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 - 5.9.2
 
 - ElasticPress version: 
 - 4.2.0
 - Elasticsearch version: 
 - Opensearch 1.2.4
 - Where do you host your Elasticsearch server? 
 - Opensaerch AWS
 - What ElasticPress features do you have currently active? 
 - Post Search
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by felipeelia** [comment] 2022-05-31 15:26
The problem is already being handled in https://github.com/10up/ElasticPress/issues/2806#issuecomment-1142283294. I'm closing this one out now.

**Closed as completed by felipeelia** 2022-05-31 15:26 UTC
Labels: bug
