### ISSUE TITLE
BUG: blog_id passed to get_index_name reports array to string conversion

### ISSUE THREAD

**Issue by dingo-d** [10up/ElasticPress#4011] opened 2024-11-19 15:39 UTC
### Describe the bug

I have installed ACF Pro, as well as WPML Elasticpres plugin on my multisite website. When I try to check the index health I get a fatal error:

> Fatal error: Uncaught Error: Cannot access offset of type array in isset or empty
in /wp-content/plugins/advanced-custom-fields-pro/includes/class-acf-data.php on line 350

At first, I checked the ACF plugin (added a debugger breakpoint and checked the stack trace), and if I just added the early return there in case of an array the page worked, but the query monitor reported tons of array to string conversion warnings in the `Indexable.php` file in one of the `preg_replace` calls.

It turns out that, inside the `wp-content/plugins/ElasticPress/includes/classes/Indexable.php` file in the function `get_index_name` the `$blog_id` passed is an array that looks like this:

```php
array (
  'blog_id' => '1',
  'domain' => 'mysite.test',
  'path' => '/',
  'site_id' => '1',
  'deleted' => '0',
  'archived' => '0',
  'spam' => '0',
)
```

This is the stack trace from the debugger:

![Image](https://github.com/user-attachments/assets/711f1e63-a410-4cfb-865f-2dc36edc2af3)

So the issue is not in the ACF but in this plugin.

The parameter of the get_index_name, suggests that the `$blog_id` should be integer, but in reality, it can be either an integer or a string denoting the blog id.
WordPress isn't too strict with parameter checking so this doesn't surprise me, but I think you can do multiple things here:

1. Add a check for array and bail out early

```php
if (is_array($blog_id)) {
  return '';
}
```

2. Check if the `$blog_id` is an array, and if the `blog_id` key is set, and use it as `$blog_id`

```php
if (is_array($blog_id)) {
  if (isset($blog_id['blog_id'])) {
    $blog_id = $blog_id['blog_id'];
  }
}
```

3. Bailout if the `$blog_id` is not an integer - **wouldn't suggest this as the parameter is a mix between integers and strings**
4. Bailout if the `$blog_id` is not an integer or a string - this one is more in line with what is passed to this function, but would require a docblock change

```php
if (!is_int($blog_id) && !is_string($blog_id)) {
  return '';
}
```

I'm fine with whatever change you make (except no. 3, as that would probably break tons of things), as long as the proper types are being passed an no errors are happening.

Either way, docblock change is needed, as the types passed to this function are not just integers.

### Steps to Reproduce

1. Have a multisite WP installation
2. Use ACF Pro and WPML Elasticpress
3. Go to `/wp-admin/network/admin.php?page=elasticpress-health`
4. See a fatal error

### Environment information

OS: Mac OS Sonoma 14.7.1
Browser: MS Edge Version 131.0.2903.51 (Official build) (arm64)

### WordPress Environment ###
wp_version: 6.7
home_url: https://mysite.test
site_url: https://mysite.test
is_multisite: true
theme: redacted
plugins: redacted
revisions: 10

### Server Environment ###
php_version: 8.3.13
memory_limit: 1G
timeout: 120

Other info redacted because of company policy

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dingo-d** [comment] 2024-11-19 15:45
Looks like just returning empty is not a good workaround, so I guess the best option would be to use this:

```php
if (is_array($blog_id)) {
  if (isset($blog_id['blog_id'])) {
    $blog_id = $blog_id['blog_id'];
  }
}
```

**Comment by felipeelia** [comment] 2024-11-21 18:15
@dingo-d it seems the problem is/was actually in WPML's plugin and a fix was already merged [here](https://github.com/OnTheGoSystems/wpml-elasticpress/pull/47).

**Closed as completed by felipeelia** 2024-11-21 18:15 UTC
Labels: bug

**Comment by dingo-d** [comment] 2024-11-22 07:17
Seems like they didn't release this in the 2.0.3 version of the plugin I got from their premium download. Will try to ping them about it.

I think it would be good to update your docblocs, and add some extra guard checks for the type safety, just in case 👍🏼
