### ISSUE TITLE
BUG: English (United States) cannot be selected as the Elasticsearch Language

### ISSUE THREAD

**Issue by JakePT** [10up/ElasticPress#3601] opened 2023-08-15 12:24 UTC
### Describe the bug

When editing the ElasticPress settings the English (United States) language cannot be selected.

### Steps to Reproduce

1. Go to _ElasticPress > Settings_.
2. Select _English (United States)_ for the _Elasticsearch Language_.
3. The page will reload with whatever was previously selected still selected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MARQAS** [comment] 2023-08-29 14:54
This is the known issue in WordPress core: https://core.trac.wordpress.org/ticket/58284
As we are using the explicit value for English as en_US, the WordPress Core is not updating the selected value properly. 
We will keep this ticket open until the issue gets resolved in Core(so we can double-check if everything is working or not)

Also, please note that it won't affect the functionality, the issue is only with the display of dropdown.

**Comment by felipeelia** [comment] 2023-10-03 14:05
Closing as there is nothing we can do at this point.

**Closed as completed by felipeelia** 2023-10-03 14:05 UTC
Labels: bug
