### ISSUE TITLE
Indexing comments?

### ISSUE THREAD

**Issue by qubika** [10up/ElasticPress#238] opened 2015-04-09 09:43 UTC
Is is possible to index comments in ElasticPress so that they form part of the search? 

I'm using the P2 theme so comments and posts have equal weighting - since EP doesn't seems to support comment indexing (unless I'm missing something) then this is a limitation.

**Comment by tlovett1** [comment] 2015-04-09 14:05
Right now this is not possible. I do think this would be great as a separate plugin or an enhancement. PRs welcome!

**Comment by shadyvb** [comment] 2017-11-27 17:51
Hey folks! I stumbled upon this issue while searching for the same feature, got an extension started at https://github.com/humanmade/elasticpress-comments .

**Comment by rmccue** [comment] 2019-06-01 15:01
With ElasticPress' 3.0 update introducing Indexables, is comment support under way already? I see it mentioned in the docs and the 3.0 blog post.

**Comment by tlovett1** [comment] 2019-08-29 04:28
@rmccue yes, should be around in the next 6 months.

**Comment by brandwaffle** [comment] 2021-04-09 17:38
Comments Indexable is scheduled for 3.6 release. PR/further info in #1531. Closing this ticket as a duplicate of that one.

**Closed by brandwaffle** 2021-04-09 17:38 UTC
Labels: enhancement
