### ISSUE TITLE
Enabling facets kills off taxonomy archives for custom post types

### ISSUE THREAD

**Issue by Pezzab** [10up/ElasticPress#1073] opened 2018-05-01 08:45 UTC
Is this a bug, question or feature request?
Bug

Describe the issue you encountered:
If I enable facets my taxonomy archives no longer display custom post types (just shows regular posts unrelated to the selected tag)

Current WordPress version:
4.9.5

Current ElasticPress version:
2.5

Current Elasticsearch version:
5.5.0

Where do you host your Elasticsearch server:
Linode

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
Pods
Elasticsearch Autosuggest
Admin Columns

**Comment by tlovett1** [comment] 2018-05-02 01:45
Should be fixed in 2.5.1. Can you confirm?

**Comment by Pezzab** [comment] 2018-05-02 09:55
OK that's great - my taxonomy archives are working again.

The only weird thing that is happening is that I can see the Facet widget and set it up in admin but it doesn't show up at the front end (neither does the related posts widget for that matter).

**Comment by kevinsan2001** [comment] 2018-05-02 12:48
2.5.1. Update. Facets working on Archive and Search pages. Facets and Related Posts not visible on custom category and taxonomy pages. Elasticpress works with URL - http://localhost/1/networks/?filter_database=no. So the facets can be built with php $_GET variables. The Facets disappeared with the new update. Is this by design or a bug? Thank you for the great plugin.

**Comment by allan23** [comment] 2018-05-08 16:56
@Pezzab and @kevinsan2001, can you let us know which theme(s) you are using?

**Comment by kevinsan2001** [comment] 2018-05-13 11:43
http://underscores.me. I have also disabled Wordpress jquery and use the latest jquery.  Sorry for the delay. I did not see the response. I fine with the 2.5 version.

**Comment by thomasplevy** [comment] 2018-06-07 00:37
FWIW on 2.5.2 my custom post type archives show empty results with faceting enabled.

Attempting to use the Facet or Related Post widgets when viewing a custom post type single pages results in them not being displayed at all. I've been looking through the code of the plugin and it seems like this may be intentional but I'm not entirely certain why...

**Comment by allan23** [comment] 2018-08-30 19:32
@kevinsan2001 and @thomasplevy are you both using a multisite install?
It could be the related to #334 .

**Closed by allan23** 2018-08-30 19:32 UTC
