### ISSUE TITLE
Extend Custom Field Synchronization Beyond Meta

### ISSUE THREAD

**Issue by SumnanAzadi** [10up/ElasticPress#3801] opened 2023-12-31 06:10 UTC
### Describe your question

Hello there,

I am working on enhancing data synchronization within ElasticPress. I've already implemented selective synchronization for meta fields using the `ep_prepare_meta_data` hook, which works well to include only the meta fields I specify.

I would like to replicate this functionality for other fields—such as terms, comments, or any custom data fields—essentially, fields that are not part of the metadata.

The goal is to have a similar mechanism where I can define which specific fields are synchronized, to improve performance and relevance of the data being handled.

Could you please provide guidance or point me to the appropriate hooks/methods that can be used to achieve selective synchronization for these other fields?

Any advice or direction would be greatly appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment] 2024-01-04 16:12
Hi @SumnanAzadi,

You can utilize the [ep_post_sync_args_post_prepare_meta](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L539) filter, which allows you to customize the post fields as needed including the terms.

As this is not a bug and no additional input is needed, I'm closing this issue.

Regards,
Burhan

**Closed as completed by burhandodhy** 2024-01-04 16:12 UTC
Labels: question
