### ISSUE TITLE
Low indexing speed

### ISSUE THREAD

**Issue by olexandrrevizor** [10up/ElasticPress#1677] opened 2020-02-26 19:52 UTC
Hi. I have a blog that contains 14k posts and tried to add these posts to the elastic search index. 
I indexed some of the posts, but it's extremely slow, and it will take about 6 hours to estimate. All the performance optimization tips from the official site I made. In my opinion, I removed the redundant data such as post meta. Can I increase indexing speed? Add the index configuration below:
```
{
  "test-post-1" : {
    "aliases" : { },
    "mappings" : {
      "date_detection" : false,
      "properties" : {
        "ID" : {
          "type" : "long"
        },
        "guid" : {
          "type" : "keyword"
        },
        "menu_order" : {
          "type" : "long"
        },
        "permalink" : {
          "type" : "keyword"
        },
        "post_content" : {
          "type" : "text"
        },
        "post_date" : {
          "type" : "date",
          "format" : "yyyy-MM-dd HH:mm:ss"
        },
        "post_excerpt" : {
          "type" : "text"
        },
        "post_id" : {
          "type" : "long"
        },
        "post_mime_type" : {
          "type" : "keyword"
        },
        "post_modified" : {
          "type" : "date",
          "format" : "yyyy-MM-dd HH:mm:ss"
        },
        "post_name" : {
          "type" : "text",
          "fields" : {
            "post_name" : {
              "type" : "text"
            },
            "raw" : {
              "type" : "keyword",
              "ignore_above" : 10922
            }
          }
        },
        "post_parent" : {
          "type" : "long"
        },
        "post_status" : {
          "type" : "keyword"
        },
        "post_title" : {
          "type" : "text",
          "fields" : {
            "post_title" : {
              "type" : "text",
              "analyzer" : "standard"
            },
            "raw" : {
              "type" : "keyword",
              "ignore_above" : 10922
            },
            "sortable" : {
              "type" : "keyword",
              "ignore_above" : 10922,
              "normalizer" : "lowerasciinormalizer"
            }
          }
        },
        "post_type" : {
          "type" : "text",
          "fields" : {
            "post_type" : {
              "type" : "text"
            },
            "raw" : {
              "type" : "keyword"
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "5000"
          },
          "ignore_malformed" : "true"
        },
        "number_of_shards" : "1",
        "provided_name" : "test-post-1",
        "max_shingle_diff" : "8",
        "max_result_window" : "1000000",
        "creation_date" : "1582745447768",
        "analysis" : {
          "filter" : {
            "shingle_filter" : {
              "max_shingle_size" : "5",
              "min_shingle_size" : "2",
              "type" : "shingle"
            },
            "edge_ngram" : {
              "min_gram" : "3",
              "side" : "front",
              "type" : "edgeNGram",
              "max_gram" : "10"
            },
            "ewp_word_delimiter" : {
              "type" : "word_delimiter",
              "preserve_original" : "true"
            },
            "ewp_snowball" : {
              "type" : "snowball",
              "language" : "russian"
            }
          },
          "normalizer" : {
            "lowerasciinormalizer" : {
              "filter" : [
                "lowercase",
                "asciifolding"
              ],
              "type" : "custom"
            }
          },
          "analyzer" : {
            "ewp_lowercase" : {
              "filter" : [
                "lowercase"
              ],
              "type" : "custom",
              "tokenizer" : "keyword"
            },
            "shingle_analyzer" : {
              "filter" : [
                "lowercase",
                "shingle_filter"
              ],
              "type" : "custom",
              "tokenizer" : "standard"
            },
            "default" : {
              "filter" : [
                "ewp_word_delimiter",
                "lowercase",
                "stop",
                "ewp_snowball"
              ],
              "char_filter" : [
                "html_strip"
              ],
              "language" : "russian",
              "tokenizer" : "standard"
            }
          }
        },
        "number_of_replicas" : "1",
        "uuid" : "cWGjSF4FQ1Or0A_0oSlA2g",
        "version" : {
          "created" : "7050299"
        }
      }
    }
  }
}

```

**Comment by olexandrrevizor** [comment] 2020-02-26 19:58
Wordpress version: 5.3.2
Elasticsearch version: 7.5.2
Enabled plugins: ElasticPress

**Comment by mustafauysal** [comment] 2020-03-03 13:37
Hi @olexandrrevizor,

Do you sync using CLI or dashboard? 

If you use the dashboard, can you reduce "Content Items per Index Cycle" options under `ElasticPress > Settings`? (You can use `--per-page` parameter to set that value in case you use CLI.)

**Comment by olexandrrevizor** [comment] 2020-04-18 08:01
I used cli. I tried different batch size, but have the same effect

**Comment by oscarssanchez** [comment] 2020-05-08 01:14
Hi @olexandrrevizor , 

In my experience, reducing the per page items results in a greater indexing time. 

Based on experience, I've seen different results depending on these parameters that have not being mentioned yet:

* Your service resources
* Your posts size. This is especially true if you are indexing large files like extremely big PDF's which will result in greater indexing time. 

It would be great to know if you solved this and if not please let us know. To test if it could be your service you can try elasticpress.io which offers a free trial for you to test. This is tailored to work best with ElasticPress, so this would rule out immediately that the problem could be your service.

**Comment by oscarssanchez** [comment] 2020-05-19 13:44
Hi, 

We are closing now this issue as there was no further follow up. If the issue is still not solved, Please feel free to reopen or submit a new issue referencing this one. Thanks!

**Closed by oscarssanchez** 2020-05-19 13:44 UTC
Labels: question
