### ISSUE TITLE
[terms] query does not support [publish] within lookup element

### ISSUE THREAD

**Issue by CyberCyclone** [10up/ElasticPress#2066] opened 2021-02-03 06:12 UTC
This is an extension to this bug after changing 'from' to equal 0: https://github.com/10up/ElasticPress/issues/2065

**Describe the bug**
```
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[terms] query does not support [publish] within lookup element","line":135,"col":40}],"type":"parsing_exception","reason":"[terms] query does not support [publish] within lookup element","line":135,"col":40},"status":400}
```

**Steps to Reproduce**

1. Added 'ep_prepare_meta_data' function found here: https://elasticpress.zendesk.com/hc/en-us/articles/360052019111
2. Set the settings found here:
![image](https://user-images.githubusercontent.com/4373888/106704383-c3d9d700-6637-11eb-86ae-2eb4efc034f1.png)

3. Do a search with Wordpress
4. Generated query (after fixing the ```'from': ""``` bug):
```
{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "function_score": {
            "query": {
                "bool": {
                    "should": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "bool": {
                                            "should": [
                                                {
                                                    "multi_match": {
                                                        "query": "trump",
                                                        "type": "phrase",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1",
                                                            "terms.category.name^1",
                                                            "terms.post_tag.name^1"
                                                        ],
                                                        "boost": 3
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "trump",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1",
                                                            "terms.category.name^1",
                                                            "terms.post_tag.name^1"
                                                        ],
                                                        "type": "phrase",
                                                        "slop": 5
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ],
                                "filter": [
                                    {
                                        "match": {
                                            "post_type.raw": "post"
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "bool": {
                                "must": [
                                    {
                                        "bool": {
                                            "should": [
                                                {
                                                    "multi_match": {
                                                        "query": "trump",
                                                        "type": "phrase",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1"
                                                        ],
                                                        "boost": 3
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "trump",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1"
                                                        ],
                                                        "type": "phrase",
                                                        "slop": 5
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ],
                                "filter": [
                                    {
                                        "match": {
                                            "post_type.raw": "page"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
            "functions": [
                {
                    "exp": {
                        "post_date_gmt": {
                            "scale": "14d",
                            "decay": 0.25,
                            "offset": "7d"
                        }
                    }
                }
            ],
            "score_mode": "avg",
            "boost_mode": "sum"
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "post",
                            "page",
                            "product"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": {
                            "publish": "publish",
                            "inherit": "inherit"
                        }
                    }
                }
            ]
        }
    }
}
```

**Expected behavior**
Return the results.

**Environment information**
 - Device: Cloudways
 - OS: N/A
 - Browser and version: N/A
 - WordPress version:  5.5.3

**Comment by felipeelia** [comment] 2021-02-05 16:18
Hi @CyberCyclone ,

I can't reproduce it locally. Are you by any chance hooking some custom code to a filter like `ep_formatted_args` or `ep_post_formatted_args`? Theoretically, [this line here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L1347) would prevent "post_status" from being an indexed array. Thanks!

**Comment by CyberCyclone** [comment] 2021-02-09 01:02
Hi @felipeelia,

It's probably going to take a while to debug as the website I'm working on has over 500,000 posts, so any re-index will take time.

The only one I'm tapping into is this code exactly:

```
add_filter( 'ep_prepare_meta_data', function( $meta ) {  
    $allowed_meta = array( 'post_views_count' );
    $all_meta = $meta;
    $meta = [];    
    
    foreach( $allowed_meta as $meta_key ) {
        if (array_key_exists($meta_key, $meta)) {
            $meta[$meta_key] = $all_meta[$meta_key];
        }
    }
    return $meta; 
} );
```
The website I'm working on has over 500,000 posts so I was hitting the ES 5000 field limit. After filtering with 'ep_prepare_meta_data' the '5000 field limit' error went away. 

**The original bug has actually resolved itself.** From memory, I had this turned off which I think is what was causing this bug:
![image](https://user-images.githubusercontent.com/4373888/107300040-6ecd1380-6ac4-11eb-92eb-62203d53c672.png)

I now have a different bug that's very similar. When I run the query, it's doing 2 queries:
![Screen Shot 2021-02-09 at 10 57 00 am](https://user-images.githubusercontent.com/4373888/107300657-ae482f80-6ac5-11eb-8e95-88dea8a43697.png)

Compared to the above query in this issue, it's adding more to the query:
![image](https://user-images.githubusercontent.com/4373888/107300354-1a766380-6ac5-11eb-9471-4a640f2c021d.png)

Which is returning:
```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "[terms] query does not support [publish] within lookup element",
                "line": 1,
                "col": 1040
            }
        ],
        "type": "parsing_exception",
        "reason": "[terms] query does not support [publish] within lookup element",
        "line": 1,
        "col": 1040
    },
    "status": 400
}
```

Specifically, the first query is the failing one:
```
{
    "from": 0,
    "size": 10,
    "sort": [
        {
            "_score": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "function_score": {
            "query": {
                "bool": {
                    "should": [
                        {
                            "bool": {
                                "must": [
                                    {
                                        "bool": {
                                            "should": [
                                                {
                                                    "multi_match": {
                                                        "query": "apple",
                                                        "type": "phrase",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1",
                                                            "terms.category.name^1",
                                                            "terms.post_tag.name^1"
                                                        ],
                                                        "boost": 3
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "apple",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1",
                                                            "terms.category.name^1",
                                                            "terms.post_tag.name^1"
                                                        ],
                                                        "type": "phrase",
                                                        "slop": 5
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ],
                                "filter": [
                                    {
                                        "match": {
                                            "post_type.raw": "post"
                                        }
                                    }
                                ]
                            }
                        },
                        {
                            "bool": {
                                "must": [
                                    {
                                        "bool": {
                                            "should": [
                                                {
                                                    "multi_match": {
                                                        "query": "apple",
                                                        "type": "phrase",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1"
                                                        ],
                                                        "boost": 3
                                                    }
                                                },
                                                {
                                                    "multi_match": {
                                                        "query": "apple",
                                                        "fields": [
                                                            "post_title^1",
                                                            "post_content^1"
                                                        ],
                                                        "type": "phrase",
                                                        "slop": 5
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ],
                                "filter": [
                                    {
                                        "match": {
                                            "post_type.raw": "page"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
            "functions": [
                {
                    "exp": {
                        "post_date_gmt": {
                            "scale": "14d",
                            "decay": 0.25,
                            "offset": "7d"
                        }
                    }
                }
            ],
            "score_mode": "avg",
            "boost_mode": "sum"
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "post",
                            "page",
                            "product"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": {
                            "publish": "publish",
                            "inherit": "inherit"
                        }
                    }
                }
            ]
        }
    },
    "aggs": {
        "terms": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "post_type.raw": [
                                    "post",
                                    "page",
                                    "product"
                                ]
                            }
                        },
                        {
                            "terms": {
                                "post_status": {
                                    "publish": "publish",
                                    "inherit": "inherit"
                                }
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "category": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.category.slug"
                    }
                },
                "post_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_tag.slug"
                    }
                },
                "post_format": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.post_format.slug"
                    }
                },
                "product_cat": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_cat.slug"
                    }
                },
                "product_tag": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_tag.slug"
                    }
                },
                "product_shipping_class": {
                    "terms": {
                        "size": 10000,
                        "field": "terms.product_shipping_class.slug"
                    }
                }
            }
        }
    }
}
```

The second query is successful, however it still means that the WordPress search is not hitting ES because of the first queries failure and the whole WordPress search query takes between 6 and 10 seconds.

**Comment by felipeelia** [comment] 2021-02-09 18:54
Hi @CyberCyclone ,

Thanks for the info. Yes, what makes the query fails is this:

```
"terms": {
	"post_status": {
		"publish": "publish",
		"inherit": "inherit"
	}
}
```

Elasticsearch is not expecting an object there but an array. So, that should be

```
"terms": {
	"post_status": [
		"publish",
		"inherit"
	]
}
```

What is causing that is not clear though. In cases like these, the best way to debug is disabling all plugins, changing to a WordPress default theme, and test it again. Then you'll have to reenable everything one by one. The [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin can help you with that.

Can you please test that and let us know your findings? Thanks.

**Comment by felipeelia** [comment] 2021-03-11 14:16
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!

**Closed by felipeelia** 2021-03-11 14:16 UTC
Labels: bug, reporter feedback
