### ISSUE TITLE
QUESTION: Some posts are not indexed

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#2216] opened 2021-05-25 11:39 UTC
Hello,

I haven't been able to pinpoint yet why this happens, but some posts are not indexed properly - there are multiple authors posting content, so I can't really say what's wrong or reproduce. However, the post's content and meta look ok and aligned with the rest of the content

Has anyone encountered any similar issue and has any idea what could be wrong? Could any kind of load or background process cause this?

Also, is there any function to allow index single post reindexing?

Thank you for your time!

**Comment by Rahmon** [comment] 2021-05-25 16:19
Hi @scooterlord 

Try to run the command below to get the error message (replace ID for the ID post):

```console
wp elasticpress index --include=ID --show-errors
```

**Comment by scooterlord** [comment] 2021-05-25 22:26
Thanks! I have already re-indexed, so can't reproduce at the time, but saving this for future reference. Please leave the topic open so I can report back with the output.

Also, if anyone has encountered the same thing, please share.

**Comment by mckdemps** [comment] 2021-05-28 17:46
You can always reply to a closed issue and we can respond then.

**Comment by scooterlord** [comment] 2021-06-01 10:53
Hello again,

just came across a post that was not indexed. Here is the error I am receiving:

`[illegal_argument_exception] Limit of total fields [5000] in index [motornoidcom-post-1] has been exceeded`

Any ideas? The thing is that posts between AND after that in different categories are properly indexed - I guess it might have to do with custom fields in this category that exceeded this limit? Can I override this limit somehow?

**Comment by felipeelia** [comment] 2021-06-03 12:59
Hi @scooterlord,

For the `[illegal_argument_exception] Limit of total fields [5000] ...` error, we have it documented in the following links:

- https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-
- https://elasticpress.zendesk.com/hc/en-us/articles/360052019111

Also, your snippet should look like this: `add_filter( 'ep_total_field_limit', function() { return 15000; } );`

Here is the ES docs about it: https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-settings-limit.html

For the `[illegal_argument_exception] startOffset must be non-negative, and endOffset must be...` error:
1. Are you seeing this only on `post_name`?
2. Did you already set the correct language in EP's Settings Screen?
3. Could it be related to the length of the post_name or are you seeing this in small post names as well?

**Comment by scooterlord** [comment] 2021-06-03 20:47
@felipeelia Thanks for your support - as always!

Regarding the filter, thanks, I had no clue. It would be a good idea to have some examples in the docs.

1. Regarding the `[illegal_argument_exception] startOffset must be non-negative, and endOffset must be...` error, yes, it is encountered only in `post_name`. 
2. Regarding language, it is set as 'Greek' in the settings, however, titles are not always Greek, they are usually a mix of English and Greek.
3. I am not sure it is related to the title length. As I have stated in the example above, the `post_name` is less than 100 characters long. 

Here is the `post_title` that is converted to one `post_name` that could not be indexed:
`63934-Citroen C4 Peugeot 307 εξωτερική ασφθαλειοθήκη 6500CK 6500.CK BSM-L04 BSM-L06 ΚΑΙΝΟΥΡΓΙΑ`

The post can be indexed if I leave some spaces between `L04` and `L06`. So, after renaming the post like below it is properly indexed:
`Citroen C4 Peugeot 307 εξωτερική ασφθαλειοθήκη 6500CK 6500.CK BSM-**L 04** BSM-**L 06** ΚΑΙΝΟΥΡΓΙΑ`

Reverting back to non-space `L04` and `L06` restricts the post from being indexed.

However, I have multiple other posts, properly indexed that include `L200`,'-04',`1,3CDTi` or `2,4L`  in the title, so, other cases with mixed words that include both letters and numbers in sequence are indexed... strange, huh?

**Comment by felipeelia** [comment] 2021-06-10 13:48
Hi @scooterlord,

Unfortunately, I can't reproduce the problem. Did you make any additional changes to your mapping?

**Comment by scooterlord** [comment] 2021-06-10 14:42
@felipeelia no, nothing. I can’t reproduce myself, nor can I see easily what is not indexed because it simply does not appear in the results. I wonder if there’s a way to see what is not indexed?

**Comment by Rahe** [comment] 2021-06-22 09:46
Hello,

I have the same type of errors : 
`[illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=117,endOffset=121,lastStartOffset=120 for field 'meta.product_url.value'
`

The content of the meta.product_url.value: 
`https://clk.tradedoubler.com/click?p=260411&a=3046643&g=24714134&url=https://www.lexception.com/fr-fr/81117/sneakers-zsp4-white-zespa`

So nothing fancy here.
There is more of theses errors (23 on 7000 posts) mainly on post_content.
We haven't customized the mapping and all errors are on the offset.

**Comment by Rahmon** [comment] 2021-07-27 11:48
@scooterlord @Rahe 

I couldn't reproduce the issue either, I used Elasticsearch v5 and v7.

Maybe the issue is happening because the [token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenfilters.html) and/or [tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenizers.html) used by ElasticPress. You could test it [commenting the token filter](https://github.com/10up/ElasticPress/blob/6357996a360f2b7151c1c26ceb19f99b2cecd0b7/includes/mappings/post/7-0.php#L67), change the [tokenizer](https://github.com/10up/ElasticPress/blob/6357996a360f2b7151c1c26ceb19f99b2cecd0b7/includes/mappings/post/7-0.php#L66), and trying reindexing.

**Comment by scooterlord** [comment] 2021-07-28 17:57
@Rahmon thanks for looking into this. However, everything else now works fine and don’t want to mess it up for our increasing userbase. How else could I help out with this? Maybe share my indexing options and try to cherry-pick a couple of posts not being indexed?

**Comment by Rahmon** [comment] 2021-07-28 18:38
Since you're not facing this issue anymore and no one could replicate it, we are now closing the ticket. If you have any further questions feel free to open a new issue. Thanks!

**Closed by Rahmon** 2021-07-28 18:38 UTC
Labels: bug, high priority

**Comment by scooterlord** [comment] 2021-07-29 06:04
Ahm, I mentioned that everything else works fine - except this issue I meant :/

**Comment by scooterlord** [comment] 2021-08-09 18:31
@Rahmon Hello again, I have managed to cherry-pick a post that is not indexed. What kind of information do you want me to post?

**Comment by Rahe** [comment] 2021-08-13 13:28
Hello,

Regarding my previous comment and the other people comments, this seem to be linked to the value we want to index.
If I extract the parts that seems problematic on my comment this is :
`-zsp4`

so it seems this part is considered as "numeric" so the message saying that "startOffset must be non-negative" is like we cannot index negative numeric values.
So why this is considered like this ?

I'm on "Elasticsearch 7.10.2" by the way and schema haven't been  touched.

**Comment by scooterlord** [comment] 2022-02-16 20:50
Hello, re-opening this again. There are still some posts every now and then that are not indexed. 

- Editing and saving such a post then indexes it properly
- wp-cli re-indexing, properly indexes every single one of them

Really, I can't find anything strange as to _why_ a post is not indexed. Is there a way to somehow _lookup_ what is _not_ indexed and just index those posts? Or any other smart workaround?

**Comment by pedlima** [comment] 2022-06-14 10:55
I am having this exact error for about a month now.

Here is one (of many) examples: `514650 (Post): [illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=50680802,endOffset=50680807,lastStartOffset=50680804 for field 'post_content_filtered'`

The weird thing is, this is not even a product, it is a Landing Page from Elementor.

EDIT: Want to know the most weird thing of all? I've searched my database and there is NOTHING with "post_content_filtered"...

EDIT2: Btw, this is one example of errors in products: `458682 (Post): [illegal_argument_exception] startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=10,endOffset=15,lastStartOffset=12 for field 'post_title'`


**MY SOLUTION**

For whoever might come accross a problem like this again, this is what I ended up doing, first the trial and error:

1. Tried to sync and even tried delete and nothing was properly working
2. Tried to index via wp-cli using the command in my public_html folder "wp elasticpress index"
3. Tried to go to each of the 11 products that were giving me that error, update them (same for the landing page in Elementor) and nothing worked
4. Last thing, deleted these products that were causing problems and then it worked

But my sync was taking very long time to process, so what I ended up doing was installing a "raw" theme and putting in functions what I needed to run along my indexation process.

Then I created a file in my public_html called "elasticpress-cron.sh" (the name is not relevant, it can be anything else). This is the content for that file:

`#!/bin/bash

cd /home/customer/public_html/
/usr/local/bin/wp plugin activate maintenance
/usr/local/bin/wp theme activate twentytwentyone
/usr/local/bin/wp elasticpress index
`

The first thing here is activating a "Maintenance" plugin so that customers getting into the website won't see it broken because of a "raw" and basic theme that has to be activated next.

Inside the crontab I've inserted this line to execute that file mentioned above:
`00 06 * * * sh /home/customer/public_html/elasticpress-cron.sh`

10 minutes after this (since this actually indexes the 26k products in 5/6 minutes, there is another file named "elasticpress-cron-end.sh" that has this inside:

`#!/bin/bash

cd /home/customer/public_html/
/usr/local/bin/wp theme activate customer-theme-child
/usr/local/bin/wp plugin deactivate maintenance
`

Here the customer theme is again activated and the "Maintenance" plugin deactivated.

But then in our case there was another problem... there was a widget area that is specific from this custom theme, so therefore some widgets go to a widget area default from the other basic theme and others become inactive. So we thought in recreating that widget area in the basic theme. That did not solved the problem!

So what we ended up doing was, we changed the customer theme to have a second sidebar showing bellow the first one, so the widgets on the first one that always stay there, were left in that sidebar but the other widgets that was going into inactive widgets, were put into that second sidebar.

So that's it. All's good now and index works like a charm and fast! :)

I hope this can help someone else in the future.

**Comment by scooterlord** [comment] 2022-06-15 10:17
Hello from me as well!

After resolving a few issued with the latest version, I did **not** encounter any issues with posts not being indexed so far. A few thousands have been indexed since then without any issues.
