### ISSUE TITLE
BUG: Error establishing a database connection for syncing ~180,000 products via wp cli - 50 per page

### ISSUE THREAD

**Issue by gosixl** [10up/ElasticPress#3820] opened 2024-01-28 23:00 UTC
### Describe the bug

Hello,

I've run  `wp elasticpress sync --force --setup --show-errors --yes --post-type=product --per-page=50` to try create an index for 180,000 products. I get errors of the type: `Error: Error establishing a database connection`. I've seen the advice about decreasing size per batch from 350 to 50, no luck so far. My server has 8GB of RAM and a 2048MB RAM limit, so I'm unsure if lack of resources is an issue.

This is a consistently the kind of printout I've gotten:
```
Processed posts 144900 - 144950 of 173871. Last Object ID: 224496
Processed posts 144950 - 145000 of 173871. Last Object ID: 224436
Time elapsed: 00:00:02.000000 (+0)
Memory Usage: 2054.53mb (Peak: 2055.51mb)
Error: Error establishing a database connection.
```

In my debug logs at the time of failing i get this:
```
[28-Jan-2024 22:43:44 UTC] PHP Warning:  mysqli_real_connect(): (HY000/2002): Connection refused in /home/x.cloudwaysapps.com/x/public_html/wp-includes/class-wpdb.php on line 1987
[28-Jan-2024 22:43:45 UTC] PHP Notice:  Function wpdb was called incorrectly. wpdb must set a database connection for use with escaping. Please see <a>Debugging in WordPress</a> for more information. (This message was added in version 3.6.0.) in /home/x.cloudwaysapps.com/x/public_html/wp-includes/functions.php on line 6031
```

Our goal is to increase the number of product posts we have to 1 million. Is this plugin not suited for that scale?

### Steps to Reproduce

wp elasticpress sync --force --setup --show-errors --yes --post-type=product --per-page=50 on site with 180,000 products

### Environment information

8GB Ram Server
4 CPU Cores
100GB of free storage

### WordPress and ElasticPress information

Lastest versions as of 28 Jan 2024

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gosixl** [comment] 2024-01-29 03:23
I've just tried again at 2am and it worked with 100 per page - so perhaps the key is running the indexing at a low traffic time

**Comment by burhandodhy** [comment] 2024-01-29 09:27
Hi gosixl,

I'm glad you are able to run the sync with 100 per page. The error message indicates that the database has stopped responding. This could be due to various reasons, such as high traffic on your site or another task consuming a lot of resources. As this is not a bug and no further assistance is required, I am closing this issue.

Regards,
Burhan

**Closed as completed by burhandodhy** 2024-01-29 09:27 UTC
Labels: bug
