### ISSUE TITLE
Exclude from search results Procesing

### ISSUE THREAD

**Issue by gwhitehead** [10up/ElasticPress#3486] opened 2023-06-06 20:57 UTC
So I am just trying to understand how the Exclude from search checkbox that now exists on posts. For instance, I did some testing where this post was already published and I went in and checked it off to say exclude from ElasticPress search. Do I need to clear the index before it would be removed from search results or auto-suggest? Also it was still showing on the search results page within WordPress, Is this checkbox supposed to also remove it from the search results page? Is there a way to send a delete command to the ElasticPress database command that I am not finding in documentation? Would I be able to say sync a lower-limit-object-id and upper limit and have it recognize that an ID is no longer being included in the sync? Or do I need to trigger a resync of the entire database in order for it to recognize something that is now being excluded?

**Comment by burhandodhy** [comment] 2023-06-13 13:14
Hi @gwhitehead,

You don’t have to delete any data, perform a complete sync, or set the lower-limit-object-id or upper-limit. The “Exclude from search” feature operates by ensuring that when users enable this option for a published post, the post should no longer show up in search results or auto-suggestions. However, considering your case where the post is still appearing on the front page, it’s likely that there is some code preventing the `exclude_from_search` meta from being indexed. To further debug the issue, could you please verify if there is any code in place that handles this functionality?

**Is there a way to send a delete command to the ElasticPress database command that I am not finding in documentation?**
You can use the eval command to execute the code line that deletes the post. Here’s an example of how you can use it: `wp eval '\ElasticPress\Indexables::factory()->get( "post" )->delete( "$object_id" );'`

Regards,
Burhan

**Comment by gwhitehead** [comment] 2023-06-16 15:12
To update, I did find a filter to pre_get_posts and after turning off that filter I was able to see that the exclude checkbox was working. 

If documents is enabled in the features menu, I don't see the checkbox to exclude from search results, am i missing something?

**Comment by felipeelia** [comment] 2023-06-22 12:43
Glad to see you have that working @gwhitehead. Regarding don't seeing the checkbox when the Documents feature is enabled, I'm not able to reproduce that. That checkbox is displayed when the "Post Search" feature is enabled, do you have that enabled too?

**Comment by gwhitehead** [comment] 2023-06-22 12:59
What I am meaning is, within the Media Library. I am not seeing the ability to exclude a PDF item in the media library from being indexed like I am for the other post types. So with Documents enabled and it crawling uploaded files within the media library, I am not seeing a way to mark something in the media library as something to exclude.

**Comment by felipeelia** [comment] 2023-06-26 19:03
Ah, makes total sense @gwhitehead. That is not a feature we have at the moment but certainly a good enhancement we could work on. I'll close this issue now but I've opened #3514 so we can work on that specific enhancement. Thanks!

**Closed as completed by felipeelia** 2023-06-26 19:03 UTC
