### ISSUE TITLE
Elasticpress not working

### ISSUE THREAD

**Issue by Alexpalix** [10up/ElasticPress#3752] opened 2023-11-04 16:04 UTC
### Describe your question

Hi! My dev came up with this short video https://www.loom.com/share/ef480fc4a64b4a4899bb9e8a4bd9a180?sid=fa19ce8b-e2fc-4066-a502-effccc348c50 we cannot seem to get the plugin working. Please can you help us?

Alex

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickchomey** [comment] 2023-11-04 22:53
My immediate impression is that the elasticsearch service is not accessible due to some sort of Azure firewall or other access settings. 

Unless you can share some sort of error message from the wordpress debug log, or do some deeper debugging to identify what the issue is (looking at what error message comes back when elasticpress tries to connect), it seems like a question for Azure more than elasticpress.

**Comment by nickchomey** [comment] 2023-11-04 22:55
Better yet, try connecting to the azure elasticsearch instance from your command line rather than elasticpress.

**Comment by felipeelia** [comment] 2023-11-06 15:53
Hi @Alexpalix, @nickchomey was spot on: you need to make sure the webserver running your WordPress installation can connect to that address. Sending a curl call from within the server or something similar would be your dev's first step toward that.

As we do not provide support for infrastructure configuration, I'm going to close the issue now.

**Closed as completed by felipeelia** 2023-11-06 15:53 UTC
Labels: question
