### ISSUE TITLE
Conflict with bbpress

### ISSUE THREAD

**Issue by CannedBear** [10up/ElasticPress#536] opened 2016-07-23 11:03 UTC
Hi,

it looks like elasticpress is preventing bbpress from loading single entries and replies. When I activate elasticpress they are gone, when I deactivate elasticpress they show up again.

I am using 
bbPress Version 2.5.10 
ElasticPress Version 2.0

**Comment by tlovett1** [comment] 2016-07-24 18:24
Can you try the develop branch of ElasticPress (2.1)?

**Comment by tlovett1** [comment] 2016-07-25 14:13
Just fixed in the develop branch.

**Comment by CannedBear** [comment] 2016-07-25 17:14
Hi,
I updated to 2.1 and activated bbPress in the new elasticpress dashboard. Still single entries and replies are not shown. It loads only the reply form, but not the entry. 

for example:
erlebnis.world/foren/thema/bitte-beachten/

**Comment by egadriandroid** [comment] 2016-10-05 08:55
Hi mate,
I also find when elasticpress plugin activated the keymaster of forum cannot reply/edit/trash/spam.
When I trash/spam the post in topics it gives me "ERROR: You do not have the permission to do that! "
I noticed this conflict is same when Yoast SEO plugin activated too.

**Comment by Ritesh-patel** [comment] 2016-12-13 16:24
Hi @egadriandroid 

I have checked with bbPress 2.5.12 and ElasticPress develop branch code but could not reproduce this. Are you using latest version of plugins? Also can you check if it's ElasticPress conflict and not some other plugin/theme?

Regards,
Ritesh

**Comment by Ritesh-patel** [comment] 2017-01-03 17:29
Hello,

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh

**Closed by Ritesh-patel** 2017-01-03 17:29 UTC
Labels: bug
