### ISSUE TITLE
QA Version 2.2

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#632] opened 2016-11-15 13:19 UTC
2.2 beta has been pushed to the development branch (see readme.txt for list of updates).

We need to QA all the feature API changes. Also, the `must not` tax query code seems to be off. I left a todo in the API class about it.

**Comment by Ritesh-patel** [comment] 2016-11-15 19:03
I found 2 issues while doing QA

- In the changelog it says, "Modules are now auto-on", but when I update from 2.1.2 to 2.2, all the features were off.
- While doing index using CLI, I got following notice in error log 
```
Notice: ep_elasticsearch_alive is <strong>deprecated</strong> since version ElasticPress 2.1! Use ep_elasticsearch_can_connect() instead.
```

#633 fixes deprecated notice and tax query issue.

**Comment by Ritesh-patel** [comment] 2016-11-17 17:19
ed3de5b7d1ac23109e1ecc0012f43bb06e29f36a fixes the feature auto-update issue on plugin update.

**Comment by j3j5** [comment] 2016-11-18 17:28
I am testing this branch and I've encountered a lot of this errors on the ES servers while building the index:

```
Nov 18 17:24:53 : org.elasticsearch.index.mapper.MapperParsingException: failed to parse
Nov 18 17:24:53 :         at org.elasticsearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:175) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:69) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:274) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:529) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:506) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:174) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:179) ~[elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:351) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.bulk.TransportShardBulkAction.index(TransportShardBulkAction.java:158) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.bulk.TransportShardBulkAction.handleItem(TransportShardBulkAction.java:137) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.bulk.TransportShardBulkAction.onPrimaryShard(TransportShardBulkAction.java:123) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.bulk.TransportShardBulkAction.onPrimaryShard(TransportShardBulkAction.java:74) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:78) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:50) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:903) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:873) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:319) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:254) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:839) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:836) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:142) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1651) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:848) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:271) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:250) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:242) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.1.jar:5.0.1]
Nov 18 17:24:53 :         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
Nov 18 17:24:53 :         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
Nov 18 17:24:53 :         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Nov 18 17:24:53 : Caused by: java.lang.ClassCastException
```
The command doesn't throw any errors, but I can see these on the journal of the ES server. Not sure how to debug them. Any idea how I can help?

**Comment by Ritesh-patel** [comment] 2016-11-18 18:39
Hi @j3j5 

Which version of Elasticsearch you are using? We had this issue during upgrading of Elasticsearch version but has been fixed. Please make sure you have up to date copy of develop branch.

**Comment by j3j5** [comment] 2016-11-18 18:45
Hi @Ritesh-patel  

I am using Elasticsearch 5.0.1 with the latest develop branch, including your PR #633 merged.

I tried first with 2.1.2 and had these exceptions, then upgraded to the version mentioned above and rebuilt the index, the same exceptions appeared again while processing.

**Comment by Ritesh-patel** [comment] 2016-11-18 20:26
Hi @j3j5 

I just checked with Elasticsearch 5.0.1 and not able to reproduce this issue. Can you give us any more detail which can help us to debug the issue you are facing?

Regards,
Ritesh

**Comment by j3j5** [comment] 2016-11-18 21:04
I'd love to, what other information can I provide to help debugging the issue? 

I am not sure what is causing the errors, but after indexing the search seems to be working, so I'm not sure what issues that exception is causing (maybe missing posts on the index? it's hard to say since my indice has quite a lot).

As I said, please tell me what can I do to provide more useful info.

Thanks.

**Comment by j3j5** [comment] 2016-11-19 00:02
I was wrong, after trying to reindex it seems the index isn't being built after all. Running `wp elasticpress status` returns empty indexes on all shards :(

Output can be seen here: http://pastebin.com/X5hwkish

**Comment by Ritesh-patel** [comment] 2016-11-22 10:53
Hi @j3j5 

Can you pass `--setup` flag while doing index? it will force it to put mappings again. That should work.

Regards,
Ritesh

**Comment by j3j5** [comment] 2016-11-22 17:22
Hi Ritesh,

I've tracked down the error and it seems my posts have a very big number of info on the `meta` and `post_meta` fields, and this was causing problems when indexing. I've modified the mapping and the post info using the filters (`ep_config_mapping_file` and  `ep_post_sync_args_post_prepare_meta`) and now it's working like a charm.

At first I discovered I was hitting `Limit of total fields [1000] in index [xxxxx] has been exceeded`, which could be fixed by changing the `index.mapping.total_fields.limit` setting on the mapping, but when I did that I discover some other errors (numeric values out of range for long and others), it was then when I realized there was a big amount of data I didn't need to be indexed at all so, once I've removed it all is clear and indexing and searching works like expected.

I'll leave this here in case it can help somebody else.

Thanks for the good work!

**Closed** 2017-01-30 20:28 UTC

**Comment by tonybahama** [comment] 2018-06-24 19:02
@j3j5 Hi! Can you please post an example for the filters you used? What meta did you find unnecessary?

**Comment by j3j5** [comment] 2018-06-25 17:23
@tonybahama I think it really depends on your specific situation. 

On my case we were indexing different kind of posts and didn't need the meta data on most types except on attachments, so we have something like:

```php
// Remove all meta and post meta info from post before indexing.
    add_filter('ep_post_sync_args_post_prepare_meta', function($post) {
        switch($post['post_type']) {
            case 'announcement':
            case 'page':
            case 'post':
            case 'quotes':
                unset($post['meta']);
                unset($post['post_meta']);
                break;
            case 'attachment':
                // Remove useless info
                unset($post['meta']);
                unset($post['post_meta']['useless_key']);
                if (empty($post['post_meta'])) {
                    unset($post['post_meta']);
                }
                break;
            default:
                break;
        }
        return $post;
    });
```

Good luck!
