### ISSUE TITLE
Unable to connect after upgrade

### ISSUE THREAD

**Issue by dfroberg** [10up/ElasticPress#854] opened 2017-06-01 16:33 UTC
Upgraded elasticpress from 2.2.1 to 2.3 with EP_HOST set in wp-config, after the update it refuses to connect. Never ending "Fix it".

Have the http_request_args to enable self-signed SSL certs, It doesn't seem to matter if this filter is active or not.

Ideas?

**Comment by dfroberg** [comment] 2017-06-05 15:34
Oddly enough it seems to be syncing new articles to the ES server even though the message to fix it is still there.

**Comment by tlovett1** [comment] 2017-06-05 20:26
@ivankristianto mind taking a look at this?

**Comment by ivankristianto** [comment] 2017-06-06 04:45
@tlovett1 yes talked about this yesterday with @allan23.
It might have permission/capability issue to check the plugin list for Ingest Attachment.
But I want to make sure, because I cannot reproduce this issue on local instance. Need to try with other ES provider.

**Comment by ivankristianto** [comment] 2017-06-06 04:46
@dfroberg what is your ES provider? or where you host your ES service?

**Comment by dfroberg** [comment] 2017-06-06 11:30
AWS ES via NGINX Proxy

**Comment by tlovett1** [comment] 2017-06-07 14:41
@ivankristianto can you prioritize this one?

**Comment by ivankristianto** [comment] 2017-06-11 13:32
@dfroberg 
I did try your settings but I cannot replicate your issue.
Can you install debug bar plugin + debug-bar-elasticpress plugin, and then send the result to my email: ivan.kristianto[at]10up.com?
I provide the screenshot of which data i would like to see.
![elasticpress 10up wordpress](https://user-images.githubusercontent.com/656006/27011395-02bea09a-4ee5-11e7-83f5-1c37b09a858f.jpg)

And read more here: https://www.elasticpress.io/blog/2017/05/debugging/

**Comment by dfroberg** [comment] 2017-06-13 14:53
Hmm I'm not getting anything in ES Debug bar output

**Comment by ivankristianto** [comment] 2017-06-18 17:57
@dfroberg are you still seeing an issue connecting to your ES?

**Comment by dfroberg** [comment] 2017-06-20 10:07
Yep, the Fix message persists

**Comment by ivankristianto** [comment] 2017-06-20 10:25
@dfroberg i can't say for sure, probably you need to revisit your settings with your proxy. That might cause this issue. The issue from the WordPress is it cannot connect well to your ES server.

**Comment by dfroberg** [comment] 2017-06-20 10:29
It's odd, because it still indexes articles, and curl can reach it fine from the servers on the VPC;
`
root@amnfrontend-master:~# curl https://search.internal.almasdarnews.com --insecure
{
  "name" : "Ardina",
  "cluster_name" : "823627428757:amn",
  "version" : {
    "number" : "2.3.2",
    "build_hash" : "72aa8010df1a4fc849da359c9c58acba6c4d9518",
    "build_timestamp" : "2016-11-14T15:59:50Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
`

**Comment by dfroberg** [comment] 2017-06-20 10:37
Switching to http rather than https in wp-config after enabling the port 80 on nginx proxy solves the issue, which leads me to believe that the functions.php addition of http_request_args to enable self-signed SSL certs is somehow not doing its job in the new version, perhaps a clue?

**Comment by ivankristianto** [comment] 2017-06-20 10:58
this plugin depends on wp_remote_request when talking to elasticsearch server. You can see it more in this code: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L2090

Can you try one thing for me? 
If you don't use document feature, can you please disable this line: https://github.com/10up/ElasticPress/blob/develop/elasticpress.php#L61
And let me know if that notice gone.

**Comment by dfroberg** [comment] 2017-06-20 11:02
Yup re-enabling https and removing the require_once did the trick

**Comment by ivankristianto** [comment] 2017-06-20 11:08
Great! 
I know where it goes wrong, thank you so much for helping and report this issue.
The issue is document feature request elasticsearch version too early in this line: https://github.com/10up/ElasticPress/blob/develop/features/documents/documents.php#L199
so your `http_request_args` has no effect.
 
I'm closing this issue and open another ticket and will get this fix in next release.

**Comment by tlovett1** [comment] 2017-06-26 02:01
@dfroberg @ivankristianto features are setup on plugins loaded so this makes sense. I could be convinced that we should setup features on after_theme_setup. For now, it makes sense to add your code to an mu-plugin.

**Comment by tlovett1** [comment] 2017-06-27 16:07
@ivankristianto to test moving feature setup to init

**Closed** 2017-10-31 12:00 UTC
Labels: bug
