### ISSUE TITLE
Limit facets widget to categories with content

### ISSUE THREAD

**Issue by roditi3811** [10up/ElasticPress#1664] opened 2020-02-15 22:13 UTC
Is there a possibility to limit the results shown in facets widget?
Currently the widget shows all the categories/taxonomies, etc. from the website, when I browse through the websites categories, even if some of them have 0 results.
How can I eliminate them? This is not very useful for a site with a lot of categories / taxonomies. 
Thanks!

![cat](https://user-images.githubusercontent.com/60715009/74595952-e5ba0280-5050-11ea-94e2-3e1088a18ea7.png)

**Comment by oscarssanchez** [comment] 2020-05-08 01:28
Hi @roditi3811 ,

I think what you can do in this case is use the facet filter widget `ep_facet_search_widget` to customize what would you like to display. This way, you also have more control over the customization of the widget. 

Hope this helps

**Comment by oscarssanchez** [comment] 2020-05-19 13:44
Hi, 

We are closing now this issue as there was no further follow up. If the issue is still not solved, Please feel free to reopen or submit a new issue referencing this one. Thanks!

**Closed by oscarssanchez** 2020-05-19 13:44 UTC
