### ISSUE TITLE
Private Products - Order Search - Caching

### ISSUE THREAD

**Issue by thachphamw2** [10up/ElasticPress#1720] opened 2020-03-27 18:38 UTC
Hello,

Thank you for creating the awesome plugin to connect with Elasticsearch. Currently, I have 2 problems, can you guys please take a look at it?

1/ Exclude private posts on the search results.

I have the private posts/products and it keeps showing up on the search result page, which shouldn't be.

How can I exclude them from the search result?

2/ After activate the plugin, the search behaviors changed.

I.E my order code is "#GS-10018 Johnny Deep", by searching for "10018" it won't work. While the normal search will work fine.

3/ Caching problem

I optimize my site with the plugin W3 Total Cache, and here's my config

- Memcache (page cache)
- Database Cache (Redis)
- Object cache (Redis)

After activating W3 Total Cache on, the header on the search page didn't appear x-powered-by-elastic press.

I have disabled database cache, it didn't work also.

Thank you!

**Comment by oscarssanchez** [comment] 2020-05-08 02:09
Hi @thachphamw2 ,

To answer some of your questions:

1/ Exclude private posts on the search results.

Can you confirm there is no other custom code running in your site and you are running the latest version of elasticpress? As far as I could test, protected content only enables unpublish status post search in the backend

2/ After activate the plugin, the search behaviors changed.

Some behaviors are expected to change, this sounds like this issue https://github.com/10up/ElasticPress/issues/1307 Can you try the solution proposed there?

3/ Caching problem

Would you be able to disable caching on your search/archive page ? Unfortunately i don't have expertize with the W3 Total Cache so my guesses are limited there.

**Comment by oscarssanchez** [comment] 2020-05-19 13:43
Hi, 

We are closing now this issue as there was no further follow up. If the issue is still not solved, Please feel free to reopen or submit a new issue referencing this one. Thanks!

**Closed by oscarssanchez** 2020-05-19 13:43 UTC
Labels: question
