### ISSUE TITLE
BUG: Oxygen Builder doesn't load with v3.6.6 enabled

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2562] opened 2022-01-20 05:26 UTC
With the latest ElasticPress v3.6.6 plugin enabled, when trying to open up Oxygen Builder's page builder, it will start loading and then freeze up the whole tab, to the extent that my computers 32gb ram becomes 97% used!

With the ElasticPress plugin disabled, Oxygen Builder loads normally.

Currently running Oxygen Builder v3.9

**Comment by felipeelia** [comment] 2022-01-20 16:19
Since Oxygen Builder is a paid codebase, we aren’t able to readily troubleshoot this compatibility issue. If you are able to reach out and get the authors of this code to share a copy with us for testing purposes only, please let us know in this forum and we’ll provide you a link to securely share it with us. Thanks

**Comment by shmaltz** [comment] 2022-01-20 16:56
Hi @felipeelia , Thanks for your quick response!
You can technically test Oxygen Builder here: https://oxygenbuilder.com/try/ but I'm not sure if the error Will be reproducible without elasticsearch on the server.

If you provide me a secure link to upload, I can provide you with the latest version of oxygen for testing.

**Comment by shmaltz** [comment] 2022-01-24 05:45
https://github.com/soflyy/oxygen-bugs-and-features/issues/2703

**Comment by felipeelia** [comment] 2022-01-25 21:30
Hi @shmaltz,

Can you please upload it to https://transfer.10up.com/ and send us the link via the form in https://www.elasticpress.io/request-a-demo/ (just select "Not sure yet" as the product). Thanks

**Comment by shmaltz** [comment] 2022-01-25 22:05
@felipeelia Done.

**Comment by felipeelia** [comment] 2022-01-26 14:10
Hi @shmaltz,

I'm able to reproduce it to some extent: for me, it only happens with Oxygen's WooCommerce elements. Any other seems to work fine. It is not something related to ElasticPress 3.6.6 though, as I was able to reproduce the same behavior using ElasticPress 3.6.5.

Although we strive to keep ElasticPress compatible with all plugins possible, as you've already communicated them the problem, being Oxygen a paid plugin and this bug a non-obvious issue (there is no AJAX request hanging or something similar, as far as I can see), I'm going ahead and closing the issue. Feel free to drop here any details you can share on how to reproduce the problem, this may help future users of both plugins.

Thanks

**Closed by felipeelia** 2022-01-26 14:10 UTC
Labels: bug
