### ISSUE TITLE
Adding custom meta to highlighed text

### ISSUE THREAD

**Issue by tobiushirogeri** [10up/ElasticPress#2285] opened 2021-08-02 19:16 UTC
Hello, I'm trying to add my custom meta to the list of highlighted fields to no avail.
I've added the **ep_highlighting_fields** and **ep_formatted_args** filter the the required fields and added my custom meta 
```
 add_filter('ep_highlighting_fields', function($fields, $formatted_args, $args){
[...]
 $fields[] = '_field_text_en';
 $fields[] = '_field_text_fr';
     return $fields;
}, 10, 3);
```

But the only returned highlighted fields are "post_title" and "post_content"  in my post object
`
$post->highlight["post_title"][0]
Dévoilement de notre nouveau <mark class="ep-highlight">plan</mark> <mark class="ep-highlight">d’action</mark> de développement durable.
`
There should be an highlight for the post meta too since 

`
$post->meta["_field_text_fr"][0]["value"]
Nous sommes heureux de vous dévoiler notre tout nouveau Plan d’action 
`
Thanks for your time !

**Comment by Rahmon** [comment] 2021-09-15 16:35
Hi @tobiushirogeri 

I've tested it and I could reproduce this bug. We'll put it on our radar. Thanks!

**Comment by Rahmon** [comment] 2021-12-23 18:06
After an initial investigation, I could reproduce the issue but it seems that is something with Elasticsearch since the field is sent by the request from ElasticPress to Elasticsearch.

I've found some issues relating to this:

- https://github.com/elastic/elasticsearch/issues/26230
- https://github.com/elastic/elasticsearch/pull/26305 (PR that fixed the previous issue)

Although the PR was merged, the issue is happening on Elasticsearch 5.6.16. It's necessary to keep investigating to check if it still happens on Elasticsearch 7.

**Comment by Rahmon** [comment] 2022-01-11 12:58
To highlight a custom field (meta or not), the field should be included in the search.

For example, to add the meta field `_field_text_en` we need to add the field to the search and to highlight:

```php
// Add field to the search
add_filter( 'ep_weighting_configuration_for_search', function ( $weight_config, $args ) {
	$post_type = (array) $args['post_type'];

	if ( in_array( 'post', $post_type, true ) ) {
		$weight_config['post']['meta._field_text_en.value'] = array(
			'weight'  => 1,
			'enabled' => 1,
		);
	}

	return $weight_config;
}, 10, 2);

// Add field to highlight
add_filter( 'ep_highlighting_fields', function( $fields ){
	$fields[] = 'meta._field_text_en.value';

   	return $fields;
} );
```
I've tested it on 5.2, 5.6, and 7.9 versions of Elasticsearch.

**Closed** 2022-01-11 18:08 UTC
Labels: confirmed bug
