### ISSUE TITLE
cannot use ep_es_info_cache_expiration filter from app/theme

### ISSUE THREAD

**Issue by rlaan** [10up/ElasticPress#961] opened 2017-10-31 15:24 UTC
Dear ElasticPress developers, thanks for this great plugin to interact with ElasticSearch!

I'm glad that caching the ES information is now available in the plugin.
I tried to leverage the build in filter to change the expiration time from 5 minutes to 1 day, however my filter code wasn't activated. I tracked it down to being a timing issue: the apply_filter call had already taken place before my add_filter code was run. 
Could the call to relevant code which needs the version be delayed?

My WordPress version: 4.8.2
My ElasticPress version: 2.3.2
My Elasticsearch version: 5.1.1
My Elasticsearch server: Amazon

Other plugins installed: nothing out of the ordinary

Steps to reproduce:

1. add filter in theme (app)
2. call wp-admin elasticpress settings page
3. check for existence of filter function on apply_filter call => in my case the should be added filter was missing.

Thanks,
Ruud

**Comment by eugene-manuilov** [comment] 2017-11-01 12:52
Hi @rlaan,

This happens because it is triggered in a function which is bounded to the `plugins_loaded` action. That's why your code in a theme doesn't work. I'll update it to be triggered in the `init` action to allow theme authors to override too.

**Comment by rlaan** [comment] 2017-11-01 13:08
Hi Eugene,

That would be great! 

Thanks so much.
Ruud

**Comment by eugene-manuilov** [comment] 2017-11-03 12:16
Hi @rlaan,

the Pull Request has been approved and merged into develop branch. Could you please grab develop version and test it on your end to make sure it works as intended now on your end?

**Comment by rlaan** [comment] 2017-11-06 12:33
Hi Eugene,

I cloned the develop version and the filter is now calling my theme function. 
Works perfectly.
Thanks!

**Closed** 2018-02-13 05:27 UTC
Labels: enhancement

**Comment by jbjanot** [comment] 2025-01-07 13:52
Hi,

Sorry to resurrect this thread, but it seems I can't add a filter to the hook `ep_es_info_cache_expiration` from the theme.
The hook is triggered, but probably not at the right time to be used when the transient `ep_es_info` is set.
I might be missing something.

Thank you for your help!

**Comment by 6th-avenue** [comment] 2025-01-07 14:17
Hi Jean-Baptiste, 

Disclaimer: I have not used the EP plugin since 2017, so it may have become totally different.

Can you share how & when you are attempting to use this filter? 
Your filter should become available before 'init' is triggered. 

Cheers, 
Ruud

**Comment by jbjanot** [comment] 2025-01-07 14:38
Hi Ruud,

Thanks for taking the time to look at that.
I call the filter from a class instantiated from the functions.php, as soon as the theme is ready.
There is nothing fancy, here is an extract:


```php
/**
 * Class construct
 */
public function __construct() {
	add_filter( 'ep_es_info_cache_expiration', array( $this, 'ep_es_info_cache_expiration' ) );
}

/**
 * Reduces the frequency of the elasticsearch informations updates
 * as it is not going to be updated very often
 *
 * @return int
 */
public function ep_es_info_cache_expiration(): int {
	return WEEK_IN_SECONDS;
}
```

I debug the transients with a plugin that lists all the transients set, and even when my filter is set, it keep being set to 5 minutes instead of a week.
I tried to create a simple plugin, and then the filter was applied and I saw in the transients is set to 1 week before expiration.
So my guess is that the filter is applied too early, before the theme is set.

For information, the place the filter is applied is [there](https://github.com/10up/ElasticPress/blob/develop/includes/classes/Elasticsearch.php#L1572).
(includes/classes/Elasticsearch.php:1572)

I suppose that the filter is now applied elsewhere since 2017.

Thanks for your help!

**Comment by 6th-avenue** [comment] 2025-01-07 14:50
Hi Jean-Baptiste,

With the link you provided I tried (but failed) to find when this code is being called.
I guess your assumption could be correct, it may be called before the theme is set. 

Since this issue was/is closed, perhaps open up a new issue for this again? 
I think that would trigger the attention of the developers more.

Best of luck,
Ruud
