### ISSUE TITLE
prepare_post() in class-ep-api.php called 49 times when creating a shop_order post via WC Rest API

### ISSUE THREAD

**Issue by sumudumathew** [10up/ElasticPress#1030] opened 2018-02-22 16:04 UTC
Have you searched for similar issues before submitting this one? Yes

Is this a bug, question or feature request? bug, probably will end up being a feature

Describe the issue you encountered: We are using 'ep_post_sync_args' filter to add line_items and coupon data to the orders (type: shop_order). While a doing full we noticed that 'ep_post_sync_args' was called 49 times when creating a order via WC Rest using the following request,
/wc/v2/orders
request body:{"customer_id":"2","status":"pending"}
We tried to use the 'ep_pre_index_post' filter but found out that this filter does not get called in when doing a full sync via the Woocommerce / ElasticPress dashboard.

I believe the solution would be to add the 'ep_pre_index_post' or a similar filter to line: 564 in class-ep-dashboard.php after the line, $post_args = ep_prepare_post( get_the_ID() );

Current WordPress version: 4.9.4

Current ElasticPress version: 2.4.2

Current Elasticsearch version: 3.3.2

Where do you host your Elasticsearch server: searchly.com

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): Woocommerce Stripe

Steps to reproduce:

1. Add a echo or error_log message to the function applying the filter, ep_post_sync_args
2. Send the Woocommerce Rest request via, /wc/v2/orders
request body:{"customer_id":"2","status":"pending"}
**Note: I suspect this does not have to be a Woocommerce request**
3. Count the number of times the error_log message appears in the log file.

Screenshots, if needed:

**Comment by nprasath002** [comment] 2018-02-24 12:56
`prepare_post()` is called everytime a post meta is updated to check whether to do a sync with ES. What problems you encounter when its called multiples times?

**Comment by sumudumathew** [comment] 2018-02-26 10:31
The issue is that we enriching the post with additional attributes when the post_type is 'shop_order' and when a shop_order is created by Woocommerce ep_post_sync_args. This means if 10000 orders are created ep_post_sync_args filter called 49000 times which is a scaling issues for us.

A better solution could be to provide a filter when doing a full sync (bulk index) in line: 564 in class-ep-dashboard.php after the line, $post_args = ep_prepare_post( get_the_ID() );

**Comment by nprasath002** [comment] 2018-03-06 18:06
Working on a fix for this. Will update once i am complete

**Comment by Gandhi11** [comment] 2019-03-05 14:13
Any news on this one?

**Comment by bengreeley** [comment] 2019-07-02 21:22
@Ritesh-patel @allan23 I can't tell - was this ever merged and fixed? I think the files have been refactored quite a bit so it's difficult to tell if the issue remains or not. Let me know if you think it's good and I can update the plugin to the latest version. A site is currently using Ritshes fork because it implemented this performance fix. Thanks!

**Comment by tlovett1** [comment] 2019-09-03 19:04
I'm also wondering if this was fixed. @oscarssanchez ?

**Comment by oscarssanchez** [comment] 2022-04-05 16:23
For me it doesn't log the error message  more than once, but I get this weird output:

<img width="1320" alt="Screen Shot 2022-04-05 at 11 21 37" src="https://user-images.githubusercontent.com/31049169/161800532-3ba2935e-10fd-42d7-b6f7-9662cd22c97f.png">

**Comment by felipeelia** [comment] 2022-04-12 17:22
We discussed it and as it is not possible to reproduce the problem with the current codebase -- the logic around that filter changed quite a bit in the 3.0 rewrite --, we are closing it out.

**Closed by felipeelia** 2022-04-12 17:22 UTC
Labels: confirmed bug
