### ISSUE TITLE
Got 500 error

### ISSUE THREAD

**Issue by kevin25** [10up/ElasticPress#958] opened 2017-10-26 02:06 UTC
I got warning on backend:

`Your Elasticsearch version 5.6.3 is above the maximum required Elasticsearch version 5.3. ElasticPress may or may not work properly.`

When navigate to:
 /shop/something-here/?attribute_style=Sweatshirt&attribute_color=Navy&attribute_size=M

I got 500 error and saw this on error log:

`2017/10/26 02:02:50 [error] 7242#0: *610529 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/domain/public_html/wp-content/plugins/elasticpress/classes/class-ep-api.php on line 228" while reading response header from upstream, client: 66.249.66.29, server: domain.com, request: "GET /shop/something-here/?attribute_style=Sweatshirt&attribute_color=Navy&attribute_size=M HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com"
`

I disable ElasticPress and it works again.

**Comment by lukaspawlik** [comment] 2017-10-26 08:02
Hi,

Is there any chance you can increase memory limit for PHP script?

Adding following to `wp-config.php` (or replacing if similar declaration already exists):

```
define( 'WP_MEMORY_LIMIT', '1024M' );
```

Can you also check that your installation has disabled `WP_DEBUG` mode? It can also be increasing overall memory usage.

will double maximum memory usage for PHP script.

Above error occurs when ElasticPress plugin decodes response from Elasticsearch server.

This is not a bug in plugin itself so I suggest bumping memory limit for PHP script.

**Comment by kevin25** [comment] 2017-10-26 12:19
@lukaspawlik  It's not memory. I set memory up to 2G. It's elasticsearch version. I set up Elasticsearch 5.6 while the max version is 5.5. I cloned the dev repo and it works.

**Comment by lukaspawlik** [comment] 2017-10-26 12:40
Hi @kevin25 ,

Thank you for getting back to me. Can you let me know what exactly you did?

Did you bump your memory limit to `2G` and you were still getting error `500` on that page with Fatal Error in logs? Did you do both - bumping memory to limit `2G` and updating plugin to current develop version? In your initial report there are two issues: first one is a warning that `ES 5.6` is not supported by `ElasticPress 2.3.2` (but it should work correctly with it) and the second one was about hitting memory limit of `0.5G`.

I was able to use `ElasticPress 2.3.2` with `Elasticsearch 5.6` without any problems except for this warning that it's just an information about compatibility.

**Comment by kevin25** [comment] 2017-10-26 13:01
The memory has been already set before. I didn't touch it. I just removed the current stable version and cloned the dev repo. And it worked for me. There is no 500 error either.

**Comment by lukaspawlik** [comment] 2017-10-26 13:15
Thanks. I saw message `Allowed memory size of 536870912 bytes exhausted` (~520M for PHP script) that's why I mentioned about setting it higher.

I am happy that it works for you with current develop branch.

I am closing it however, feel free to re-open it if needed.

**Closed by lukaspawlik** 2017-10-26 13:15 UTC
Labels: question
