### ISSUE TITLE
ep_index_name filter and indexing problem

### ISSUE THREAD

**Issue by dnikola** [10up/ElasticPress#3952] opened 2024-07-27 05:10 UTC
### Describe your question

Hello

i am using ep_index_name filter in this way

```
add_filter( 'ep_index_name', function(  $index_name, $blog_id, $indexable ) {
	return 'myblog-post-1';
}, 10, 3 );
```

i just noticed while i am using feature to delete index and reindex all data, this make problems.
I have option checked to index posts, comments, terms and everything, and sync starts index posts, and than it index comments in same index myblog-post-1 instead of myblog-comments-1

how to prevent this?

PS. this code was proposed here on some of other topic.

Best regards

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment] 2024-08-02 06:32
Hi @dnikola,

You need to add the check based on the indexable slug. The code will look like this

```
add_filter(
  'ep_index_name',
  function ( $index_name, $blog_id, $indexable ) {
    if ( 'post' === $indexable->slug ) {
      return 'myblog-post-1';
    } elseif ( 'comment' === $indexable->slug ) {
      return 'myblog-comment-1';
    } elseif ( 'term' === $indexable->slug ) {
      return 'myblog-term-1';
    }

    return $index_name;
  },
  10,
  3
);
```

Since it’s not a bug and we don't provide support for customization, I will close this issue. Thanks

Regards,
Burhan

**Closed as completed by burhandodhy** 2024-08-02 06:32 UTC
Labels: question
