### ISSUE TITLE
Indexing with wp cli doesn't pause requests to EP.

### ISSUE THREAD

**Issue by eflorea** [10up/ElasticPress#1496] opened 2019-09-24 22:39 UTC
**Describe the bug**
On a multi-site install running elasticpress index for a specific site does not pause requests to EP.

**Steps to Reproduce**

1. Network activate EP plugin
2. Run wp cli: elasticpress index --url=subsite
3. Requests are still being made to EP while the indexing is running.

CC: @christianc1

**Comment by tlovett1** [comment] 2020-01-23 05:15
Are you saying requests are being made on parts of the site besides `subsite`? That's intended behavior.

**Comment by tlovett1** [comment] 2020-01-23 05:18
Thinking about this a bit more, here are the scenarios:
1. Active on individual site in network. Indexing without `--network-wide`
2. Network active. Indexing without `--network-wide
3. Network active. Indexing with `--network-wide

For 1, we obviously don't want to pause requests across the network.

For 2, I think we should pause requests across the network. We are currently *not* doing that.

For 3, we are correctly pausing requests across the entire network.

If we are in agreement on 2, then your PR needs to be fixed @asharirfan

**Comment by eflorea** [comment] 2020-01-23 05:28
Yes, the scenario I'm talking about is 2.

**Comment by oscarssanchez** [comment] 2021-02-03 02:01
Looks like #1647 resolved this. Closing.

**Closed by oscarssanchez** 2021-02-03 02:01 UTC
Labels: bug
