### ISSUE TITLE
Plugin compatibility issue with Perfect Woocommerce brands plugin

### ISSUE THREAD

**Issue by peeyooshk** [10up/ElasticPress#1692] opened 2020-03-10 12:11 UTC
**Describe the bug**
post upgrade to version 3.4 the plugin compatibility issue which was fixed earlier(issue 1588) has re-surfaced. The brands are missing from products post updation to 3.4.

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by tlovett1** [comment] 2020-03-10 13:55
Can you explain steps to reproduce? Right now with Perfect Brands activated locally, I'm able to see the correct products on the brands archive page. Thanks!

**Comment by peeyooshk** [comment] 2020-03-10 14:18
We noticed today only that when the plugin was activated our "brands" page on website shows the count for all brand products as "0". Also the display on frontend of single product pages does not show brand images. Post this we tested with search using a brand name and products were not shown for the related brand in search results. As a result to keep the site functioning we had to disable it.

**Comment by mustafauysal** [comment] 2020-03-10 14:19
Hi @peeyooshk,

Can you reindex the content? We made some changes after closing #1588 and it requires reindexing.

(If you updated from the develop branch earlier, you might skip that notice. )

**Comment by peeyooshk** [comment] 2020-03-10 14:46
Hello: We just un-installed the plugin, cleared cache. Re-installed from wordpress.org. We are using Amazon Elastic search. Did re-indexing and the issue exists. You can have a quick look at it here

https://www.indiefur.com/brands/

**Comment by peeyooshk** [comment] 2020-03-10 14:49
By the way after re-installation i did get the notice to re-index and it did re-index.

**Comment by peeyooshk** [comment] 2020-03-21 21:25
Any update on this?

**Comment by moraleida** [comment] 2020-03-25 18:08
@tlovett1 can you assign this to me, please?

**Comment by peeyooshk** [comment] 2020-03-31 13:07
Any update on this?

**Comment by peeyooshk** [comment] 2020-04-12 10:35
There was a new update from the plugin author of Perfect WooCommerce Brands. Can you please help if the issue is resolved or by when the fix would be released?

**Comment by moraleida** [comment] 2020-04-27 20:35
@peeyooshk is this still an issue? I see brands listed properly on the site above, in the brands page, with counts, and in individual products.

**Comment by peeyooshk** [comment] 2020-04-27 20:58
@moraleida That is because we had stopped using elasticpress since the bug was reported and are waiting for the bug to be fixed to start using it.

**Comment by peeyooshk** [comment] 2020-04-29 21:20
@tlovett1 Shall we expect an update on this bug soon or shall we start looking for an alternative? Sorry if i sound harsh, but its been over 1.5 months since the issue was reported and no workout being done to resolve the bug that we see.

**Comment by peeyooshk** [comment] 2020-07-28 16:02
@moraleida @tlovett1  Any luck on this? We would be completing 5 months in couple of days to the issue being reported and no resolution till date.

**Comment by dinhtungdu** [comment] 2020-08-06 02:56
Hi @peeyooshk, I can't reproduce your issue either. I can see the correct count on the brands page, and correct products served by ElasticPress in the brand archive page. I use WP 5.4.2 with EP 3.4.3 and Perfect Brands for WooCommerce 1.8.3

**Comment by jeffpaul** [comment] 2020-08-11 02:43
@peeyooshk we've been unable to replicate your issue.  Could you please re-test to see if things are working as expected?  If its still not working for you, then please provide your Site Health Info export to help us better troubleshoot with you... thanks!

**Comment by jeffpaul** [comment] 2020-08-19 04:07
Closing this issue for lack of response, happy to re-open if @peeyooshk confirms this is still an issue and can provide the additional details from Site Health Info.

**Closed by jeffpaul** 2020-08-19 04:07 UTC
Labels: bug, high priority, reporter feedback

**Comment by peeyooshk** [comment] 2021-02-05 10:32
The issue persists. Let me know if you want me to have this done a staging site,
