### ISSUE TITLE
"Related Posts" sometimes returns latest posts

### ISSUE THREAD

**Issue by schneyra** [10up/ElasticPress#1274] opened 2019-03-06 10:22 UTC
**Have you searched for similar issues before submitting this one?**
Yes. I've found this unanswered question on Stackoverflow: https://stackoverflow.com/questions/52141336/elasticsearch-related-posts-wordpress

**Is this a bug, question or feature request?**
This is most likely a bug.

**Describe the issue you encountered:**
I have a rather large database with about 25000 articles. I want to use Elasticsearch primarly to find related posts. On most of the articles this is working perfectly, but on many others Elasticsearch returns the just the latest posts.

**Current WordPress version:**
5.0.3

**Current ElasticPress version:**
2.8.1

**Current Elasticsearch version:**
6.3.2

**Where do you host your Elasticsearch server:**
Self-hosted

Any ideas?

**Comment by cameronterry** [comment] 2019-03-06 10:41
Hi @schneyra, thank you for reporting this.

I have a quick question; are you running a WordPress MultiSite / Network? And do you utilise a Domain Mapping plugin? And if so, do you have different domains for the admin side and the public side? For example; 

`http://admin.com/wp-admin/` (Admin) => `http://example.com/` (Mapped)

Assuming the answer to the above is yes ... one potential issue is the domain mapping plugin can alter `get_site_url()` which is used to generate the index name ElasticPress uses when communicating with Elasticsearch. This can "jump", for the lack of a better expression, giving you different index names on admin-side - where you typically index the content - and the mapped-side and can be a cause ElasticPress to return the latest posts as the mapped-side is referencing an index which either does not exist or is empty.

For reference, I've include the code in 2.8.1 which is responsible for generating the index name for clarity and better context;

https://github.com/10up/ElasticPress/blob/2.8.1/classes/class-ep-config.php#L176-L204

One potential workaround for this is use the filter, `ep_index_name` and generate an index name which is does not change with the `get_site_url()`. The specific logic will depend on whether your setup it is sub-domain or sub-folder.

**Comment by schneyra** [comment] 2019-03-06 12:44
Hi @cameronterry, thanks for the quick reply.

I'm sorry, our Admin-Area is not mapped, it's `domain.com/wp-admin/` and it is a single-site.

But speaking of the database: Our MySQL is running on a Percona Cluster, can this cause any trouble?

**Comment by schneyra** [comment] 2019-03-11 10:35
Has anyone else an idea on this topic?

**Comment by oscarssanchez** [comment] 2019-03-19 14:18
Hi @schneyra ,

When this happens, 

- Is this a specific custom post type ?
- Are you sure there's content that is related to the post?

**Comment by schneyra** [comment] 2019-03-26 15:27
Hi @oscarssanchez,

sorry for the late reply.

I am searching for related posts on the normal post-type.

I am sure, that there is related content. With about 25000 posts over about 90 categories, there should always be _something_ to find. Unfortunately, the current test-installation is on an internal staging-system of my client, which I can't show you. So, an example:

We have an article with "Passwörter" (german for "passwords") in the headline and multiple times in the content. There are several similar articles in the database, that also contain "Passwörter" in title and body. Those articles are also in the same category. Related posts are queried with `$related_posts = ep_find_related(get_the_ID(), 6);`

When I use the search with the term "passwörter", which also operates on the elasticsearch database, those articles are found.

This is the query body for the related-posts, that I got from the debug-bar:

```json
{
    "from": 0,
    "size": 6,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "more_like_this": {
            "like": {
                "_id": 228421
            },
            "fields": [
                "post_title",
                "post_content",
                "terms.post_tag.name"
            ],
            "min_term_freq": 1,
            "max_query_terms": 12,
            "min_doc_freq": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "term": {
                        "post_type.raw": "post"
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                }
            ]
        }
    }
}
```

This is the Query Body of the search:
```
{
    "from": 0,
    "size": 40,
    "sort": [
        {
            "post_date": {
                "order": "DESC"
            }
        },
        {
            "ID": {
                "order": "DESC"
            }
        }
    ],
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": "passwu00f6rter",
                        "type": "phrase",
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.post_tag.name",
                            "terms.category.name",
                            "post_author.login"
                        ],
                        "boost": 4
                    }
                },
                {
                    "multi_match": {
                        "query": "passwu00f6rter",
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.post_tag.name",
                            "terms.category.name",
                            "post_author.login"
                        ],
                        "boost": 2,
                        "fuzziness": 0,
                        "operator": "and"
                    }
                },
                {
                    "multi_match": {
                        "fields": [
                            "post_title",
                            "post_content",
                            "post_excerpt",
                            "terms.post_tag.name",
                            "terms.category.name",
                            "post_author.login"
                        ],
                        "query": "passwu00f6rter",
                        "fuzziness": 1
                    }
                }
            ]
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must_not": {
                            "terms": {
                                "post_id": [
                                    244128
                                ]
                            }
                        }
                    }
                },
                {
                    "terms": {
                        "post_type.raw": [
                            "post",
                            "page",
                            "attachment",
                            "recruiting-days",
                            "firmenpraes"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish",
                            "acf-disabled"
                        ]
                    }
                }
            ]
        }
    }
}
```

**Comment by schneyra** [comment] 2019-03-28 16:12
Can I provide you more informations to help you, @oscarssanchez ?

**Comment by schneyra** [comment] 2019-04-04 06:57
I've installed the latest update and reindexed the site, with the same results. Any ideas?

**Comment by oscarssanchez** [comment] 2019-05-30 01:02
Hi @schneyra ,

Per reading documentation on More like this https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

It looks like the cause may be here on max_query_terms as documentation states:

max_query_terms: The maximum number of query terms that will be selected. Increasing this value gives greater accuracy at the expense of query execution speed. Defaults to 25.

So my guess is that this may not be ideal for all scenarios. I think having the ability to edit these params could be a step forward to enable developers to experiment and find the sweet spot for their particular use case. I will bring this to our standup.

**Comment by oscarssanchez** [comment] 2019-07-08 15:25
Closing per #1355

**Closed by oscarssanchez** 2019-07-08 15:25 UTC
