### ISSUE TITLE
BUG: WooCommerce Orders page not showing orders

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2223] opened 2021-06-01 00:31 UTC
When the ElasticPress plugin is enabled, users cannot see their previous orders on `My Account -> Orders`.
All orders are only visible on the backend.
Once I disable ElasticPress, the orders show up again.
DebugBar 0 ElasticPress queries on the My Account page.

Indexing protected content is enabled.
Woocommerce indexing is enabled

Is this normal behavior? 

Is there anything I can do to disable ElasticPress on specific pages?

Thank you!

**Comment by shmaltz** [comment] 2021-06-01 04:28
I fixed this temporarily by putting a `pre_get_posts` with `$query->set( 'ep_integrate', false );` right before the [my_account] shortcode.

This is probably just a bandaid fix, and I would love to know why this is happening.

Thanks!

**Comment by jeffpaul** [comment] 2021-06-01 15:53
Noting here that this may be related to a similarly reported issue on the WooCommerce Conversion Tracking by woopt plugin: https://wordpress.org/support/topic/critical-uncaught-exception/#post-14505512

**Comment by felipeelia** [comment] 2021-06-03 13:29
Hi @shmaltz,

I could not reproduce this one in a fresh install. Are you by any chance changing the meta fields that are allowed to be indexed? WooCommerce relies on a `_customer_user` meta field to connect the order to its user, so if you are not indexing that field, that is probably the issue.

@jeffpaul I gave a look at that topic, but it really seems to be something related to the "WooCommerce Conversion Tracking by woopt" plugin. I've subscribed to the topic anyway, let's see what are the results from their tests.

Thanks!

**Comment by shmaltz** [comment] 2021-06-03 15:02
You are awesome @felipeelia!

I was only indexing the `_sku` meta field (because when indexing all fields, the indexing would time out and not complete. This seemed like the only fix). Are there any other important meta fields that I should be indexing too?

Here is my code:

```
add_filter('ep_prepare_meta_data', function ($meta) {
    $allowed_meta = array('_sku'); // To add more meta keys, just add a comma e.g. '_sku', 'price', etc.
    $all_meta = $meta;
    $meta = [];

    foreach ($allowed_meta as $meta_key) {
        $meta[$meta_key] = $all_meta[$meta_key];
    }
    return $meta;
});
```

**Comment by felipeelia** [comment] 2021-06-03 17:04
Hey @shmaltz, I'm happy to know it worked!

You probably will want to index all the meta we have listed here: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/WooCommerce/WooCommerce.php#L50

I'm now closing the issue but feel free to reopen it or create a new one if needed. Thanks!

**Closed by felipeelia** 2021-06-03 17:04 UTC
Labels: bug

**Comment by shmaltz** [comment] 2021-06-04 04:57
@felipeelia Thank you.

I added all the fields to my function, however now I am getting lots of Undefined Index errors (one error per meta field) in Query Monitor, and when using `--show-bulk-errors` in wp-cli, it is filled with these same errors.

Is there any way to prevent these notices?

**Here is the function I used:**
`add_filter('ep_prepare_meta_data', function ($meta) {
    $allowed_meta = array('_thumbnail_id',
    '_product_attributes',
    '_wpb_vc_js_status',
    '_swatch_type',
    'total_sales',
    '_downloadable',
    '_virtual',
    '_regular_price',
    '_sale_price',
    '_tax_status',
    '_tax_class',
    '_purchase_note',
    '_featured',
    '_weight',
    '_length',
    '_width',
    '_height',
    '_visibility',
    '_sku',
    '_sale_price_dates_from',
    '_sale_price_dates_to',
    '_price',
    '_sold_individually',
    '_manage_stock',
    '_backorders',
    '_stock',
    '_upsell_ids',
    '_crosssell_ids',
    '_stock_status',
    '_product_version',
    '_product_tabs',
    '_override_tab_layout',
    '_suggested_price',
    '_min_price',
    '_customer_user',
    '_variable_billing',
    '_wc_average_rating',
    '_product_image_gallery',
    '_bj_lazy_load_skip_post',
    '_min_variation_price',
    '_max_variation_price',
    '_min_price_variation_id',
    '_max_price_variation_id',
    '_min_variation_regular_price',
    '_max_variation_regular_price',
    '_min_regular_price_variation_id',
    '_max_regular_price_variation_id',
    '_min_variation_sale_price',
    '_max_variation_sale_price',
    '_min_sale_price_variation_id',
    '_max_sale_price_variation_id',
    '_default_attributes',
    '_swatch_type_options',
    '_order_key',
    '_billing_company',
    '_billing_address_1',
    '_billing_address_2',
    '_billing_city',
    '_billing_postcode',
    '_billing_country',
    '_billing_state',
    '_billing_email',
    '_billing_phone',
    '_shipping_address_1',
    '_shipping_address_2',
    '_shipping_city',
    '_shipping_postcode',
    '_shipping_country',
    '_shipping_state',
    '_billing_last_name',
    '_billing_first_name',
    '_shipping_first_name',
    '_shipping_last_name');
    $all_meta = $meta;
    $meta = [];
    foreach ($allowed_meta as $meta_key) {
        $meta[$meta_key] = $all_meta[$meta_key];
    }
    return $meta;
});`


**Here is a sample of the errors in CLI:**
`Notice: Undefined index: _billing_first_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_first_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_last_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _thumbnail_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _product_attributes in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _wpb_vc_js_status in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _swatch_type in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: total_sales in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _downloadable in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _virtual in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _regular_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _sale_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _tax_status in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _tax_class in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _purchase_note in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _featured in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _weight in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _length in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _width in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _height in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _visibility in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _sku in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _sale_price_dates_from in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _sale_price_dates_to in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _sold_individually in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _manage_stock in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _backorders in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _stock in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _upsell_ids in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _crosssell_ids in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _stock_status in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _product_version in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _product_tabs in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _override_tab_layout in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _suggested_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _customer_user in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _variable_billing in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _wc_average_rating in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _product_image_gallery in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _bj_lazy_load_skip_post in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_variation_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _max_variation_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _max_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_variation_regular_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _max_variation_regular_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_regular_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _max_regular_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_variation_sale_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _max_variation_sale_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _min_sale_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _max_sale_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _default_attributes in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _swatch_type_options in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _order_key in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_company in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_address_1 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_address_2 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_city in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_postcode in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_country in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_state in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_email in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_phone in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_address_1 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_address_2 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_city in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_postcode in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_country in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _shipping_state in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402
Notice: Undefined index: _billing_last_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-funct`

**Comment by alewolf** [comment] 2021-06-05 04:18
> Noting here that this may be related to a similarly reported issue on the WooCommerce Conversion Tracking by woopt plugin: https://wordpress.org/support/topic/critical-uncaught-exception/#post-14505512


Hi. I'm the developer of the "WooCommerce Conversion Tracking by woopt" plugin. 

I'm using a function on the purchase confirmation page to retrieve the order ID from WP query. It seems that function breaks if your plugin is enabled. 

Here's the function: 

```php
    protected function get_order_from_order_received_page()
    {
        global $wp;

        $order_id = absint($wp->query_vars['order-received']);

        $order = new WC_Order($order_id);

        if (empty($order_id) || $order_id == 0) {

            return false;
        } else {
            return $order;
        }
    }
```

It seems that your ElasticPress plugin is changing the default behaviour of WP query, which leads to the issue. 

Do you see a way how to fix this?

**Comment by shmaltz** [comment] 2021-06-09 22:33
@felipeelia Any idea how to get rid of these `Notice: Undefined index:` errors when using the function?


> 
> 
> @felipeelia Thank you.
> 
> I added all the fields to my function, however now I am getting lots of Undefined Index errors (one error per meta field) in Query Monitor, and when using `--show-bulk-errors` in wp-cli, it is filled with these same errors.
> 
> Is there any way to prevent these notices?
> 
> **Here is the function I used:**
> `add_filter('ep_prepare_meta_data', function ($meta) { $allowed_meta = array('_thumbnail_id', '_product_attributes', '_wpb_vc_js_status', '_swatch_type', 'total_sales', '_downloadable', '_virtual', '_regular_price', '_sale_price', '_tax_status', '_tax_class', '_purchase_note', '_featured', '_weight', '_length', '_width', '_height', '_visibility', '_sku', '_sale_price_dates_from', '_sale_price_dates_to', '_price', '_sold_individually', '_manage_stock', '_backorders', '_stock', '_upsell_ids', '_crosssell_ids', '_stock_status', '_product_version', '_product_tabs', '_override_tab_layout', '_suggested_price', '_min_price', '_customer_user', '_variable_billing', '_wc_average_rating', '_product_image_gallery', '_bj_lazy_load_skip_post', '_min_variation_price', '_max_variation_price', '_min_price_variation_id', '_max_price_variation_id', '_min_variation_regular_price', '_max_variation_regular_price', '_min_regular_price_variation_id', '_max_regular_price_variation_id', '_min_variation_sale_price', '_max_variation_sale_price', '_min_sale_price_variation_id', '_max_sale_price_variation_id', '_default_attributes', '_swatch_type_options', '_order_key', '_billing_company', '_billing_address_1', '_billing_address_2', '_billing_city', '_billing_postcode', '_billing_country', '_billing_state', '_billing_email', '_billing_phone', '_shipping_address_1', '_shipping_address_2', '_shipping_city', '_shipping_postcode', '_shipping_country', '_shipping_state', '_billing_last_name', '_billing_first_name', '_shipping_first_name', '_shipping_last_name'); $all_meta = $meta; $meta = []; foreach ($allowed_meta as $meta_key) { $meta[$meta_key] = $all_meta[$meta_key]; } return $meta; });`
> 
> **Here is a sample of the errors in CLI:**
> `Notice: Undefined index: _billing_first_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_first_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_last_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _thumbnail_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _product_attributes in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _wpb_vc_js_status in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _swatch_type in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: total_sales in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _downloadable in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _virtual in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _regular_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _sale_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _tax_status in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _tax_class in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _purchase_note in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _featured in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _weight in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _length in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _width in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _height in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _visibility in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _sku in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _sale_price_dates_from in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _sale_price_dates_to in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _sold_individually in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _manage_stock in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _backorders in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _stock in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _upsell_ids in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _crosssell_ids in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _stock_status in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _product_version in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _product_tabs in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _override_tab_layout in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _suggested_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _customer_user in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _variable_billing in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _wc_average_rating in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _product_image_gallery in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _bj_lazy_load_skip_post in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_variation_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _max_variation_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _max_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_variation_regular_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _max_variation_regular_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_regular_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _max_regular_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_variation_sale_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _max_variation_sale_price in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _min_sale_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _max_sale_price_variation_id in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _default_attributes in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _swatch_type_options in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _order_key in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_company in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_address_1 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_address_2 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_city in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_postcode in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_country in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_state in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_email in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_phone in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_address_1 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_address_2 in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_city in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_postcode in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_country in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _shipping_state in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-functions.php on line 402 Notice: Undefined index: _billing_last_name in /var/www/site.com/htdocs/wp-content/plugins/site-functions/site-funct`
