### ISSUE TITLE
AWS elasticsearch plugins

### ISSUE THREAD

**Issue by matpol** [10up/ElasticPress#1020] opened 2018-02-06 11:25 UTC
Have you searched for similar issues before submitting this one?
yep

Is this a bug, question or feature request?
question/bug

Describe the issue you encountered:
When using AWS Elasticsearch which has Ingest Attachment Processor enabled by default (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-plugins.html) the wordpress plugin does not see the AWS elasticsearch plugins

Current WordPress version: 4.9.3 (multisite)

Current ElasticPress version: 2.4.2

Current Elasticsearch version: 6.0.1 (via AWS)

Where do you host your Elasticsearch server: AWS

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): It is a multisite and I am using the MU Domain mapper plugin with debug bar and elasticepress debug bar 

Steps to reproduce:

1. trying to enable document search it does not find ingest attachement processor
2. also tried outputting plugins as array to page - produced an empty array e.g.

```
$plugins = ep_get_elasticsearch_plugins();
$es_version = ep_get_elasticsearch_version( );

echo '<pre>';
print_r($plugins);
echo $es_version;
echo '</pre>';

```

**Comment by matpol** [comment] 2018-02-06 12:22
I think the check needs to modified to:

/_nodes/ingest

you get something like this:

```
"ingest": {
        "processors": [
          {
            "type": "append"
          },
          {
            "type": "attachment"
          },
          {
            "type": "convert"
          },
          {
            "type": "date"
          },
          {
            "type": "date_index_name"
          },
          {
            "type": "dot_expander"
          },
          {
            "type": "fail"
          },
          {
            "type": "foreach"
          },
          {
            "type": "grok"
          },
          {
            "type": "gsub"
          },
          {
            "type": "join"
          },
          {
            "type": "json"
          },
          {
            "type": "kv"
          },
          {
            "type": "lowercase"
          },
          {
            "type": "remove"
          },
          {
            "type": "rename"
          },
          {
            "type": "script"
          },
          {
            "type": "set"
          },
          {
            "type": "sort"
          },
          {
            "type": "split"
          },
          {
            "type": "trim"
          },
          {
            "type": "uppercase"
          },
          {
            "type": "user_agent"
          }
        ]
      }


```

And then you can check for attachments again

**Comment by tlovett1** [comment] 2018-02-08 16:41
What happens if you do `GET /_nodes/plugin/`? What do you see?

**Comment by matpol** [comment] 2018-02-09 08:32
I do not get anything - here is what I get with just '/_nodes/'. I have changed the cluster name.

This is from AWS
```

{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "xxxxxxxxxx",
  "nodes": {
    "pZLHOl65Qze9ifxgTGE0ow": {
      "name": "pZLHOl6",
      "version": "5.5.2",
      "build_hash": "Unknown",
      "total_indexing_buffer": 106502553,
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "os": {
        "refresh_interval_in_millis": 1000,
        "available_processors": 1,
        "allocated_processors": 1
      },
      "process": {
        "refresh_interval_in_millis": 1000,
        "id": 5242,
        "mlockall": false
      },
      "jvm": {
        "pid": 5242,
        "start_time_in_millis": 1517917717731,
        "mem": {
          "heap_init_in_bytes": 1073741824,
          "heap_max_in_bytes": 1065025536,
          "non_heap_init_in_bytes": 2555904,
          "non_heap_max_in_bytes": 0,
          "direct_max_in_bytes": 1065025536
        },
        "using_compressed_ordinary_object_pointers": "true"
      },
      "thread_pool": {
        "force_merge": {
          "type": "fixed",
          "min": 1,
          "max": 1,
          "queue_size": -1
        },
        "fetch_shard_started": {
          "type": "scaling",
          "min": 1,
          "max": 2,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "listener": {
          "type": "fixed",
          "min": 1,
          "max": 1,
          "queue_size": -1
        },
        "index": {
          "type": "fixed",
          "min": 1,
          "max": 1,
          "queue_size": 200
        },
        "refresh": {
          "type": "scaling",
          "min": 1,
          "max": 1,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "generic": {
          "type": "scaling",
          "min": 4,
          "max": 128,
          "keep_alive": "30s",
          "queue_size": -1
        },
        "warmer": {
          "type": "scaling",
          "min": 1,
          "max": 1,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "search": {
          "type": "fixed",
          "min": 2,
          "max": 2,
          "queue_size": 1000
        },
        "flush": {
          "type": "scaling",
          "min": 1,
          "max": 1,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "fetch_shard_store": {
          "type": "scaling",
          "min": 1,
          "max": 2,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "management": {
          "type": "scaling",
          "min": 1,
          "max": 5,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "get": {
          "type": "fixed",
          "min": 1,
          "max": 1,
          "queue_size": 1000
        },
        "bulk": {
          "type": "fixed",
          "min": 1,
          "max": 1,
          "queue_size": 200
        },
        "snapshot": {
          "type": "scaling",
          "min": 1,
          "max": 1,
          "keep_alive": "5m",
          "queue_size": -1
        }
      },
      "modules": [
        {
          "name": "aggs-matrix-stats",
          "version": "5.5.2",
          "description": "Adds aggregations whose input are a list of numeric fields and output includes a matrix.",
          "classname": "org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin",
          "has_native_controller": false
        },
        {
          "name": "ingest-common",
          "version": "5.5.2",
          "description": "Module for ingest processors that do not require additional security permissions or have large dependencies and resources",
          "classname": "org.elasticsearch.ingest.common.IngestCommonPlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-expression",
          "version": "5.5.2",
          "description": "Lucene expressions integration for Elasticsearch",
          "classname": "org.elasticsearch.script.expression.ExpressionPlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-mustache",
          "version": "5.5.2",
          "description": "Mustache scripting integration for Elasticsearch",
          "classname": "org.elasticsearch.script.mustache.MustachePlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-painless",
          "version": "5.5.2",
          "description": "An easy, safe and fast scripting language for Elasticsearch",
          "classname": "org.elasticsearch.painless.PainlessPlugin",
          "has_native_controller": false
        },
        {
          "name": "parent-join",
          "version": "5.5.2",
          "description": "This module adds the support parent-child queries and aggregations",
          "classname": "org.elasticsearch.join.ParentJoinPlugin",
          "has_native_controller": false
        },
        {
          "name": "percolator",
          "version": "5.5.2",
          "description": "Percolator module adds capability to index queries and query these queries by specifying documents",
          "classname": "org.elasticsearch.percolator.PercolatorPlugin",
          "has_native_controller": false
        },
        {
          "name": "reindex",
          "version": "5.5.2",
          "description": "The Reindex module adds APIs to reindex from one index to another or update documents in place.",
          "classname": "org.elasticsearch.index.reindex.ReindexPlugin",
          "has_native_controller": false
        },
        {
          "name": "transport-netty4",
          "version": "5.5.2",
          "description": "Netty 4 based transport implementation",
          "classname": "org.elasticsearch.transport.Netty4Plugin",
          "has_native_controller": false
        }
      ],
      "ingest": {
        "processors": [
          {
            "type": "append"
          },
          {
            "type": "attachment"
          },
          {
            "type": "convert"
          },
          {
            "type": "date"
          },
          {
            "type": "date_index_name"
          },
          {
            "type": "dot_expander"
          },
          {
            "type": "fail"
          },
          {
            "type": "foreach"
          },
          {
            "type": "grok"
          },
          {
            "type": "gsub"
          },
          {
            "type": "join"
          },
          {
            "type": "json"
          },
          {
            "type": "kv"
          },
          {
            "type": "lowercase"
          },
          {
            "type": "remove"
          },
          {
            "type": "rename"
          },
          {
            "type": "script"
          },
          {
            "type": "set"
          },
          {
            "type": "sort"
          },
          {
            "type": "split"
          },
          {
            "type": "trim"
          },
          {
            "type": "uppercase"
          },
          {
            "type": "user_agent"
          }
        ]
      }
    }
  }
}
```

On cloudways similar query plugins is there but empty. Ingest attachment also not available

```
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "elasticsearch",
  "nodes": {
    "_IRGvpAkSo6Ps6Ci0hoolA": {
      "name": "_IRGvpA",
      "transport_address": "127.0.0.1:9300",
      "host": "127.0.0.1",
      "ip": "127.0.0.1",
      "version": "5.4.3",
      "build_hash": "eed30a8",
      "total_indexing_buffer": 50331648,
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "settings": {
        "pidfile": "/var/run/elasticsearch/elasticsearch.pid",
        "cluster": {
          "name": "elasticsearch"
        },
        "node": {
          "name": "_IRGvpA"
        },
        "path": {
          "logs": "/var/log/elasticsearch",
          "home": "/usr/share/elasticsearch"
        },
        "default": {
          "path": {
            "data": "/var/lib/elasticsearch",
            "logs": "/var/log/elasticsearch",
            "conf": "/etc/elasticsearch"
          }
        },
        "client": {
          "type": "node"
        },
        "http": {
          "type": {
            "default": "netty4"
          }
        },
        "transport": {
          "type": {
            "default": "netty4"
          }
        }
      },
      "os": {
        "refresh_interval_in_millis": 1000,
        "name": "Linux",
        "arch": "amd64",
        "version": "4.14.14-x86_64-linode94",
        "available_processors": 6,
        "allocated_processors": 6
      },
      "process": {
        "refresh_interval_in_millis": 1000,
        "id": 28231,
        "mlockall": false
      },
      "jvm": {
        "pid": 28231,
        "version": "1.8.0_131",
        "vm_name": "OpenJDK 64-Bit Server VM",
        "vm_version": "25.131-b11",
        "vm_vendor": "Oracle Corporation",
        "start_time_in_millis": 1517902688700,
        "mem": {
          "heap_init_in_bytes": 268435456,
          "heap_max_in_bytes": 259522560,
          "non_heap_init_in_bytes": 2555904,
          "non_heap_max_in_bytes": 0,
          "direct_max_in_bytes": 259522560
        },
        "gc_collectors": [
          "ParNew",
          "ConcurrentMarkSweep"
        ],
        "memory_pools": [
          "Code Cache",
          "Metaspace",
          "Compressed Class Space",
          "Par Eden Space",
          "Par Survivor Space",
          "CMS Old Gen"
        ],
        "using_compressed_ordinary_object_pointers": "true",
        "input_arguments": [
          "-Xms256m",
          "-Xmx256m",
          "-XX:+UseConcMarkSweepGC",
          "-XX:CMSInitiatingOccupancyFraction=75",
          "-XX:+UseCMSInitiatingOccupancyOnly",
          "-XX:+DisableExplicitGC",
          "-XX:+AlwaysPreTouch",
          "-Xss1m",
          "-Djava.awt.headless=true",
          "-Dfile.encoding=UTF-8",
          "-Djna.nosys=true",
          "-Djdk.io.permissionsUseCanonicalPath=true",
          "-Dio.netty.noUnsafe=true",
          "-Dio.netty.noKeySetOptimization=true",
          "-Dio.netty.recycler.maxCapacityPerThread=0",
          "-Dlog4j.shutdownHookEnabled=false",
          "-Dlog4j2.disable.jmx=true",
          "-Dlog4j.skipJansi=true",
          "-XX:+HeapDumpOnOutOfMemoryError",
          "-Des.path.home=/usr/share/elasticsearch"
        ]
      },
      "thread_pool": {
        "force_merge": {
          "type": "fixed",
          "min": 1,
          "max": 1,
          "queue_size": -1
        },
        "fetch_shard_started": {
          "type": "scaling",
          "min": 1,
          "max": 12,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "listener": {
          "type": "fixed",
          "min": 3,
          "max": 3,
          "queue_size": -1
        },
        "index": {
          "type": "fixed",
          "min": 6,
          "max": 6,
          "queue_size": 200
        },
        "refresh": {
          "type": "scaling",
          "min": 1,
          "max": 3,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "generic": {
          "type": "scaling",
          "min": 4,
          "max": 128,
          "keep_alive": "30s",
          "queue_size": -1
        },
        "warmer": {
          "type": "scaling",
          "min": 1,
          "max": 3,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "search": {
          "type": "fixed",
          "min": 10,
          "max": 10,
          "queue_size": 1000
        },
        "flush": {
          "type": "scaling",
          "min": 1,
          "max": 3,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "fetch_shard_store": {
          "type": "scaling",
          "min": 1,
          "max": 12,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "management": {
          "type": "scaling",
          "min": 1,
          "max": 5,
          "keep_alive": "5m",
          "queue_size": -1
        },
        "get": {
          "type": "fixed",
          "min": 6,
          "max": 6,
          "queue_size": 1000
        },
        "bulk": {
          "type": "fixed",
          "min": 6,
          "max": 6,
          "queue_size": 200
        },
        "snapshot": {
          "type": "scaling",
          "min": 1,
          "max": 3,
          "keep_alive": "5m",
          "queue_size": -1
        }
      },
      "transport": {
        "bound_address": [
          "[::1]:9300",
          "127.0.0.1:9300"
        ],
        "publish_address": "127.0.0.1:9300",
        "profiles": {}
      },
      "http": {
        "bound_address": [
          "[::1]:9200",
          "127.0.0.1:9200"
        ],
        "publish_address": "127.0.0.1:9200",
        "max_content_length_in_bytes": 104857600
      },
      "plugins": [],
      "modules": [
        {
          "name": "aggs-matrix-stats",
          "version": "5.4.3",
          "description": "Adds aggregations whose input are a list of numeric fields and output includes a matrix.",
          "classname": "org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin",
          "has_native_controller": false
        },
        {
          "name": "ingest-common",
          "version": "5.4.3",
          "description": "Module for ingest processors that do not require additional security permissions or have large dependencies and resources",
          "classname": "org.elasticsearch.ingest.common.IngestCommonPlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-expression",
          "version": "5.4.3",
          "description": "Lucene expressions integration for Elasticsearch",
          "classname": "org.elasticsearch.script.expression.ExpressionPlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-groovy",
          "version": "5.4.3",
          "description": "Groovy scripting integration for Elasticsearch",
          "classname": "org.elasticsearch.script.groovy.GroovyPlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-mustache",
          "version": "5.4.3",
          "description": "Mustache scripting integration for Elasticsearch",
          "classname": "org.elasticsearch.script.mustache.MustachePlugin",
          "has_native_controller": false
        },
        {
          "name": "lang-painless",
          "version": "5.4.3",
          "description": "An easy, safe and fast scripting language for Elasticsearch",
          "classname": "org.elasticsearch.painless.PainlessPlugin",
          "has_native_controller": false
        },
        {
          "name": "percolator",
          "version": "5.4.3",
          "description": "Percolator module adds capability to index queries and query these queries by specifying documents",
          "classname": "org.elasticsearch.percolator.PercolatorPlugin",
          "has_native_controller": false
        },
        {
          "name": "reindex",
          "version": "5.4.3",
          "description": "The Reindex module adds APIs to reindex from one index to another or update documents in place.",
          "classname": "org.elasticsearch.index.reindex.ReindexPlugin",
          "has_native_controller": false
        },
        {
          "name": "transport-netty3",
          "version": "5.4.3",
          "description": "Netty 3 based transport implementation",
          "classname": "org.elasticsearch.transport.Netty3Plugin",
          "has_native_controller": false
        },
        {
          "name": "transport-netty4",
          "version": "5.4.3",
          "description": "Netty 4 based transport implementation",
          "classname": "org.elasticsearch.transport.Netty4Plugin",
          "has_native_controller": false
        }
      ],
      "ingest": {
        "processors": [
          {
            "type": "append"
          },
          {
            "type": "convert"
          },
          {
            "type": "date"
          },
          {
            "type": "date_index_name"
          },
          {
            "type": "dot_expander"
          },
          {
            "type": "fail"
          },
          {
            "type": "foreach"
          },
          {
            "type": "grok"
          },
          {
            "type": "gsub"
          },
          {
            "type": "join"
          },
          {
            "type": "json"
          },
          {
            "type": "kv"
          },
          {
            "type": "lowercase"
          },
          {
            "type": "remove"
          },
          {
            "type": "rename"
          },
          {
            "type": "script"
          },
          {
            "type": "set"
          },
          {
            "type": "sort"
          },
          {
            "type": "split"
          },
          {
            "type": "trim"
          },
          {
            "type": "uppercase"
          }
        ]
      }
    }
  }
}


```

**Comment by matpol** [comment] 2018-02-09 08:33
one other thing - if I remove the ingest plugin check in the code the it does index pdfs on AWS

**Comment by technosailor** [comment] 2018-02-12 16:00
We had problems with the Ingest plugin on AWS and spent a non-trivial amount of time talking to the AWS team. They ultimately confirmed there is a bug in their system that they need to fix. They have provided no timeline, but there is a work order. This from Dec 11, 2017.

> We have checked this with a test domain. When _nodes/plugins is queried within an instance with endpoint as localhost, the plugins does show up but when done externally through a search endpoint it doesn’t since the output is being redacted and as part of redaction the plugins list is being removed. Since _cat/plugins does show the plugin list, _nodes/plugins must also show it. This would require a change from our side.

> Therefore there is an ongoing change on the AWS Elasticsearch Environment to accommodate this identified limitation. At the moment there is no ETA for when but the issue is now known and change control process is now in place.

**Comment by nprasath002** [comment] 2018-02-13 05:18
Thanks @technosailor for the information. Marking this as closed

**Closed by nprasath002** 2018-02-13 05:18 UTC

**Comment by ethanclevenger91** [comment] 2019-11-22 01:52
@technosailor any chance you ever got an update on that bug? Seems to be an outstanding issue...

**Comment by ethanclevenger91** [comment] 2019-11-22 02:12
Anyone who finds this and doesn't want to edit the ElasticPress source, they've included a filter that thus far seems to be sufficient. I'll update if I have any issues. Keep in mind this is only helpful if you do, in fact, have the ingest attachment plugin setup on your ES instance and it isn't being reported properly, as is the case with AWS right now.

```
add_filter( 'ep_elasticsearch_plugins', function( $plugins ) {
    $plugins['ingest-attachment'] = true;
    return $plugins;
});
```

**Comment by technosailor** [comment] 2020-02-06 16:58
> @technosailor any chance you ever got an update on that bug? Seems to be an outstanding issue...

I'm no longer at Modern Tribe, @tlovett1, so I don't know if AWS ever closed the loop. I suspect they haven't though.
