### ISSUE TITLE
How to disable case sensitivity?

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#1672] opened 2020-02-23 01:57 UTC
**Describe your question**
Hello, if i search for "SaGa" it doesn't find "Saga".  (beacause the G was typed in uppercase).

**How can i make it search for the words and ignore the case?**

**Comment by mustafauysal** [comment] 2020-02-23 14:18
Hi @MediaMaquina,

I'm unable to reproduce this. Can you provide more information about your environment?

The search keywords should be case-insensitive unless you change the default mappings. Because ElasticPress supports `lowercase` filter by default https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-lowercase-tokenfilter.html

**Comment by MediaMaquina** [comment] 2020-02-23 18:59
Hi thanks for looking into it. What can i do to find the cause? i'm kinda noobie.

**Comment by mustafauysal** [comment] 2020-03-03 12:30
Hi @MediaMaquina,

Yes, I think that snippet is the reason. Because it changes the EP query for finding the "exact" phrase. 

You may consider to remove that filter or convert search term to lowercase while formatting the args.

**Comment by MediaMaquina** [comment] 2020-03-03 13:30
Hello, that code was suggested to me on here to change logic from OR to AND. I did not know it would affect case sensitivity. Is it possible to modify it to retain AND logic and not affect the case?

In the meantime i am using your second suggestion:

>  convert search term to lowercase while formatting the args.

With a code i borrowed:

```
//tolowercase search

function replace_search( $query_object )
{
    if( $query_object->is_search() ) {
        $raw_search = $query_object->query['s'];

        $replacement = strtolower($raw_search );

        if( $replacement ) {
            $query_object->set( 's', $replacement );
        }
    }
}

add_action( 'parse_query', 'replace_search' );
```
Source: https://wordpress.stackexchange.com/questions/319649/hook-to-get-and-change-the-search-string-before-processing

**Comment by felipeelia** [comment] 2020-06-05 13:52
Hi @MediaMaquina ,

We have another version of that function that can help you (and possibly others that come to this GitHub issue later):

```
function set_to_exact( $formatted_args, $args ) {
    if (
        ! empty( $formatted_args['query']['bool']['should'] ) &&
        is_array( $formatted_args['query']['bool']['should'] )
    ) {
        foreach ( $formatted_args['query']['bool']['should'] as $key => $value ) {
            if (
                ! empty( $value['multi_match']['fuzziness'] ) &&
                'auto' === $value['multi_match']['fuzziness']
            ) {
                $formatted_args['query']['bool']['should'][ $key ]['multi_match']['operator'] = 'and';
            }
        }
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );
```

As you already found a solution that fixes your problem, I'll go ahead and close this issue but feel free to reopen it or add any additional info you think is useful, okay?

Thanks!

**Closed by felipeelia** 2020-06-05 13:52 UTC
Labels: question

**Comment by MediaMaquina** [comment] 2020-06-05 14:22
I appreciate the code but i cannot use it.
It returned thousands of irrelevant posts, while in comparison the old method returns 7 relevant posts.

**Comment by felipeelia** [comment] 2020-06-05 14:41
Thanks for the feedback, @MediaMaquina . Based on the results you're getting, I'd say the `parse_query` hook solution you're already using is the best way to go. Thanks for sharing that code!

**Comment by MediaMaquina** [comment] 2020-06-05 16:08
All good thanks!!!
