### ISSUE TITLE
Indexing commenced via command-line - processed 0/0 can't stop indexing

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#2656] opened 2022-03-15 23:40 UTC
Hello everyone! I was afraid of this release, and it happened.

So I manually triggered a reindex through wp-cli, it's not working properly, I can't stop it and on the wp-admin I see processed 0/0: last object id: 0.

Any help as fast as possible would be greatly appreciated!

Edit: So I found out how to kill the process via ssh, but still the dashboard is still _running_.. :/

**Comment by brandwaffle** [comment] 2022-03-16 01:32
@scooterlord can you please share a more detailed report, including the exact cli command run, as well as the output. Thanks!

**Comment by felipeelia** [comment] 2022-03-16 10:37
@scooterlord, in addition to what @brandwaffle already said, just worth mentioning that you can run `wp elasticpress clear-index` to clear the sync status.

**Comment by scooterlord** [comment] 2022-03-16 15:12
Hello and thanks for your quick support - I ended up, shutting down the function running using kill, reverted to the old plugin and restarted the EP instance - spent a good 2 hours doing so. I think I managed to stop the sync by using the following command:
`wp eval 'delete_transient( "ep_wpcli_sync" ); delete_option( "ep_index_meta" ); delete_site_transient( "ep_wpcli_sync" ); delete_site_option( "ep_index_meta" );'`
(source: https://github.com/10up/ElasticPress/issues/1533)

The function I ran was this:
`wp elasticpress index --setup --post-type="post" --per-page=500 --show-errors`

I think I had ran the `clear-index` function with no results. 

My initial sync crashed my small EP instance due to trying to sync a lot of things - all I need synced are the posts and there's no way to select it using the wp admin panel. From admin it syncs something like 125k items while using the command line above I can only sync my posts (around 25k).

I don't know how I can contribute more to this, please let me know so I can assist. Now that I've rolled back I am too afraid to try the plugin again until I am absolutely sure it will run without issues.

**Comment by felipeelia** [comment] 2022-03-17 16:03
Hi @scooterlord,

Some questions that may help us to identify the cause of the problem:
1. When you triggered it from WP-CLI, what was the output you had there?
2. Although it is not possible to set what should be indexed in the dashboard sync, you can work with the [ep_index_posts_args](https://github.com/10up/ElasticPress/blob/4.0.1/includes/classes/Indexable/Post/Post.php#L90) filter to select what you need.
3. When you say "My initial sync crashed my small EP instance due to trying to sync a lot of things", can you please share with us how you've identified that? Timeouts, lack of space in disk, etc.
4. Do you happen to have any custom code related to ElasticPress and its hooks? If so, would it be possible for you to share it with us? That could help us to identify any possible incompatibility with the current version code.

Thanks!

**Comment by scooterlord** [comment] 2022-03-18 08:30
Hello @felipeelia once again!

Thank you for being around to provide help.

1. I cannot recall the exact output, but once it started to index, it immediately stopped, I think without giving an error. Immediately afterwards I could not initiate a new index, and from the admin I could see that a wp-cli function is running _empty_ without a way to stop it. I guess it would be a good idea since it is recognized by the admin panel, maybe you could also stop it from there.
2. Is there any documentation on how to use this function to exclude unnecessary types?
3. I am using a 1gb external server at elastic.co so when syncinc, it usually times out due to many requests. I am using the default 500. During the syncing process I can see that the elasticsearch instance is taking a lot of strain.
4. Yes, I have quite a few, but would not like to publicly share - is there some other way to share these with you?

**Comment by felipeelia** [comment] 2022-03-18 12:51
Hi @scooterlord. Some answers:

1. In regular cases it is possible to stop the wp-cli sync through the dashboard. Unfortunately, it seems in your case it got stuck in a place where it was not checking the transient responsible for that.
2. Thanks for the feedback about code snippets in the docs! The filter in question will change the WP_Query fired to get everything that should be indexed. In your case, as you want to sync only posts, it would be something like:
```
function ep_2656_ep_post_query_db_args( $args ) {
	$args['post_type'] = [ 'post' ];
	return $args;
}
add_filter( 'ep_post_query_db_args', 'ep_2656_ep_post_query_db_args' );
```
3. During the sync, ElasticPress won't send concurrent requests but -- for obvious reasons -- will send more requests than usual. If the server replies back with a 429 (too many requests in a given amount of time), it will wait 2 seconds to try again [here](https://github.com/10up/ElasticPress/blob/4.0.1/includes/classes/Indexable.php#L521).
One thing you can try is to lower the max size of requests sent, using the [ep_dynamic_bulk_max_buffer_size](https://github.com/10up/ElasticPress/blob/4.0.1/includes/classes/Indexable.php#L427) filter. Something like:
```
function ep_2656_ep_dynamic_bulk_max_buffer_size() {
	return MB_IN_BYTES;
}
add_filter( 'ep_dynamic_bulk_max_buffer_size', 'ep_2656_ep_dynamic_bulk_max_buffer_size' );
```
4. You can upload it to https://transfer.10up.com/ and share it with us via the form at https://www.elasticpress.io/request-a-demo/

Thanks!

**Comment by scooterlord** [comment] 2022-03-19 10:19
@felipeelia Thanks for the replies I will investigate further later on today and try to send the file to you.

Regarding the buffer how is this different to reducing the bulk number of posts?

**Comment by felipeelia** [comment] 2022-03-25 12:52
Hi @scooterlord,

I got a fatal error with the code you sent but couldn't reproduce the problem. FWIW, the usage of the `ep_default_index_number_of_shards` filter should be:

`add_filter( 'ep_default_index_number_of_shards', function() { return 1; } );`

To gather more info about the problem you are having, you could add to your codebase:
- This gist, so all the requests during the dynamic indexing are logged: https://gist.github.com/felipeelia/7a7a8a6bf9da15ef06c37c867eb83dbe
- The following code to see what it used to fetch content from the database:
```
add_filter(
    'ep_sync_index_args',
    function( $args ) {
        error_log( var_export( $args, true ) );
        return $args;
    }
);
```
Once you have the output of the WP-CLI command, and the logs of these two pieces of code, please share it with us and we can help investigate it further.

Answering your question, to explain the difference between reducing the buffer size or the bulk number of posts it is better to go a bit further into the indexing process. For each batch of posts:

- ElasticPress will get a number of posts from the database using a WP_Query (by default, it will get 350). This is the bulk number.
- Then these posts will be sent to Elasticsearch. Previously, EP would try to send all at once, potentially failing due to the size of the request (HTTP 413 code). With dynamic indexing, it will try to send those 350 posts in smaller chunks, adjusting the chunk size based on the success/failures of the requests.

That said, if you have 1,400 posts, you would have 4 calls to WP_Query and several requests to ES. If you set the bulk number to 200, you would have 7 calls to WP_Query and again several requests to ES. If you set it as 1,400 you would have only one call to WP_Query and the needed calls to ES (obviously there is a chance it times out as the number of things it has to deal with is bigger).

The `ep_dynamic_bulk_max_buffer_size` filter (with the `ep_dynamic_bulk_min_buffer_size` and `ep_dynamic_bulk_incremental_step` filters) will help to regulate those requests to Elasticsearch.

Does it make things clearer? Thanks!

**Comment by scooterlord** [comment] 2022-03-28 09:15
Hello @felipeelia thank you for your feedback and sorry it took me so long to respond.

Thanks for the shards code - I think it was accidentally working since it just broke the set default :D

Regarding the logging, are these logs saved on file or exposed on screen? Do I need to use these when I try to resync and also will the provide any strain to the production environment? And also I can only assume that I need to test it in the latest EP version, right? :/ So I need to time it properly so that it doesn't break functionality - currently user count is increasing so I don't want to risk it.

Your explanation about max buffer size helps a bit, from what I realize the default is 150Mb, correct? What would be a correct value to set for testing?

**Comment by scooterlord** [comment] 2022-03-31 08:18
@felipeelia Thank you once again for your reply. Creating a staging environment is out of the question for now - I know the best practice is not used in this case, but there's just not enough capacity to do so at the moment.

I might risk it at some point later during the night so I can revert back if something goes wrong and revert back to you.

**Comment by felipeelia** [comment] 2022-04-07 16:53
Okay, @scooterlord. I'm closing this issue now, if you ever get the chance to set up a staging and/or test on production overnight and can share results/discoveries here, we can reopen it. Thanks

**Closed by felipeelia** 2022-04-07 16:53 UTC
Labels: bug
